from EchoService import EchoService

class DropbackInterface_v002ConnectionHandlerImpl(DropbackInterface_v002ConnectionHandler):
    """ DropbackInterface_v002ConnectionHandlerImpl
        Handles incoming messages from dEF-Pi connections
        Generated by Python code generator for dEF-Pi at Oct 23, 2017 5:18:58 PM by coenvl
    
        NOTE: This file is generated as a stub, and has to be implemented by the user. Re-running the codegen plugin will 
        not change the contents of this file.
        
        Template by TNO, 2017 """
 
    def __init__(self, service, connection):
        """ Auto-generated constructor building the manager for the provided service """
        self.__service = service
        self.__connection = connection
    
    def handle_Reply_message(self, message):
        """ Handles messages of type Reply 
            Auto-generated method stub """


    
    def handle_Msg_message(self, message):
        """ Handles messages of type Msg 
            Auto-generated method stub """

    def on_suspend(self):
        """ Called when the connection is suspended
            Auto-generated method stub """

    def resume_after_suspend(self)
        """ Called when the connection is being suspended
            Auto-generated method stub """
        
    def on_interrupt(self)
        """ Called when the connection is interrupted
            Auto-generated method stub """
        
    def resume_after_interrupt(self)
        """ Called when the connection is restored after an interruption 
            Auto-generated method stub """
        
    def terminated(self)
        """ Called when the connection is terminated
            Auto-generated method stub """
