from abc import ABCMeta, abstractmethod

class DropbackInterface_v002ConnectionHandler:
    """ DropbackInterface_v002ConnectionHandler
        Abstract base class for connection handlers
        Generated by Python code generator for dEF-Pi at Oct 23, 2017 5:18:58 PM by coenvl
    
        NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
        
        Template by TNO, 2017 """
        
    __metaclass__ = ABCMeta        

    _NAME = "Dropback Interface"
    _VERSION = "v002"
    _RECEIVES_HASH = "93cb88bbfbd04ef32cf4be90ca2aa9d41fa2eed1f550119fc7ba7bfcd86e8240" 
    _SENDS_HASH = "93cb88bbfbd04ef32cf4be90ca2aa9d41fa2eed1f550119fc7ba7bfcd86e8240"
    _MANAGER = DropbackInterfaceConnectionManagerImpl
    _SERIALIZER = ProtobufMessageSerializer 
    _RECEIVES_TYPES = [ Reply.class, Msg.class ]
    _SENDS_TYPES = [ Reply.class, Msg.class ]

    @abstractmethod
    def handle_Msg_message(self, message): pass


    @abstractmethod
    def handle_Reply_message(self, message): pass
