from abc import ABCMeta, abstractmethod

class DropbackInterfaceV001ConnectionHandler:
    """ DropbackInterface_v001ConnectionHandler
        Abstract base class for connection handlers
        Generated by Python code generator for dEF-Pi at Oct 23, 2017 5:18:58 PM by coenvl
    
        NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
        
        Template by TNO, 2017 """
        
    __metaclass__ = ABCMeta        

    _NAME = "Dropback Interface"
    _VERSION = "v001"
    _RECEIVES_HASH = "301294bf4597dafb7c4c77bd1327e2d2129208cb820250983960853b0b6333c6" 
    _SENDS_HASH = "e612a04cb4252ff15eed647b3b98339549963298b2550567ec49f93b3f42d14"
    _MANAGER = DropbackInterfaceConnectionManagerImpl
    _SERIALIZER = ProtobufMessageSerializer 
    _RECEIVES_TYPES = [ Msg.class ]
    _SENDS_TYPES = [  ]

    @abstractmethod
    def handle_Msg_message(self, message): pass
