from abc import ABCMeta, abstractmethod

class {{vitf.handler.interface}}:
    """ {{vitf.handler.interface}}
        Abstract base class for connection handlers
        Generated by {{generator}} at {{date}} by {{username}}
    
        NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
        
        Template by TNO, 2017 """
        
    __metaclass__ = ABCMeta        

    _NAME = "{{itf.name}}"
    _VERSION = "{{vitf.version}}"
    _RECEIVES_HASH = "{{vitf.receivesHash}}" 
    _SENDS_HASH = "{{vitf.sendsHash}}"
    _MANAGER = {{itf.manager.class}}
    _SERIALIZER = {{vitf.serializer}} 
    _RECEIVES_TYPES = [ {{vitf.receiveClasses}} ]
    _SENDS_TYPES = [ {{vitf.sendClasses}} ]
{{vitf.handler.definitions}}
