from {{service.class}} import {{service.class}}

class {{vitf.handler.class}}({{vitf.handler.interface}}):
    """ {{vitf.handler.class}}
        Handles incoming messages from dEF-Pi connections
        Generated by {{generator}} at {{date}} by {{username}}
    
        NOTE: This file is generated as a stub, and has to be implemented by the user. Re-running the codegen plugin will 
        not change the contents of this file.
        
        Template by TNO, 2017 """
 
    def __init__(self, service):
        """ Auto-generated constructor building the manager for the provided service """
        self.__service = service
        
{{manager.implementations}}


package {{service.package}}.{{vitf.package}};

import javax.annotation.Generated;

import {{service.package}}.{{service.class}};
{{vitf.handler.imports}}
import org.flexiblepower.service.Connection;

/**
 * {{vitf.handler.class}}
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file is generated as a stub, and has to be implemented by the user. Re-running the codegen plugin will
 * 		 not change the contents of this file.
 * Template by TNO, 2017
 * 
 * @author {{username}}
 */
@Generated(value = "{{generator}}", date = "{{date}}")
public class {{vitf.handler.class}} implements {{vitf.handler.interface}} {

	private final Connection connection;

	private final {{service.class}} service;

	/**
	 * Auto-generated constructor for the ConnectionHandlers of the provided service
	 *
	 * @param service The service for which to handle the connections
	 */
	public {{vitf.handler.class}}(Connection connection, {{service.class}} service) {
		this.connection = connection;
		this.service = service;
	}

{{vitf.handler.implementations}}

	@Override
	public void onSuspend() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void resumeAfterSuspend() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void onInterrupt() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void resumeAfterInterrupt() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void terminated() {
		// TODO Auto-generated method stub
		
	}

}