from abc import ABCMeta, abstractmethod
from .. import {{itf.manager.class}}


class {{vitf.handler.interface}}:
    """ {{vitf.handler.interface}}
        Abstract base class for connection handlers
        Generated by {{generator}} at {{date}} by {{username}}

        NOTE: This file will be overwritten when the code generator is re-run; any user-made changes will be removed.

        Template by FAN, 2017 """

    __metaclass__ = ABCMeta

    _NAME = "{{itf.name}}"
    _VERSION = "{{vitf.version}}"
    _RECEIVES_HASH = "{{vitf.receivesHash}}" 
    _SENDS_HASH = "{{vitf.sendsHash}}"
    _MANAGER = {{itf.manager.class}}
    _SERIALIZER = {{vitf.serializer}} 
    _RECEIVES_TYPES = [{{vitf.receiveClasses}}]
    _SENDS_TYPES = [{{vitf.sendClasses}}]

{{vitf.handler.definitions}}
