# File generated by org.flexiblepower.create-service-maven-plugin
# NOTE: This file will be overwritten when the code generator is re-run; any user-made changes will be removed.
# Template by FAN, 2017

FROM {{from}}

COPY service requirements.txt /

RUN pip install --trusted-host pypi.python.org -r requirements.txt

LABEL org.flexiblepower.serviceName="{{service.name}}" 
LABEL org.flexiblepower.parameters='{{parameters}}'
LABEL org.flexiblepower.interfaces='{{interfaces}}'

ENTRYPOINT {{entrypoint}}
