from abc import ABCMeta, abstractmethod

class {{itf.manager.interface}}:
    """ {{itf.manager.interface}}
        Abstract base class for connection handler manager
        Generated by {{generator}} at {{date}} by {{username}}
    
        NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
        
        Template by TNO, 2017 """
        
    __metaclass__ = ABCMeta        

{{itf.manager.definitions}}
