class {{service.class}}:
    """ {{service.class}}
        Provides an implementation of the {{service.name}} service
        Generated by {{generator}} at {{date}} by {{username}}
    
        NOTE: This file is generated as a stub, and has to be implemented by the user. Re-running the codegen plugin will 
        not change the contents of this file.
     
         Template by TNO, 2017 """
         
    def resumeFrom(self, state):
        """ Resume this service from a previous state """

    def configure(self, config):
        """ Configure this service with the provided config """
    
    
    def modify(self, config):
        """ Modify the configuration with the provided config """
    
    def suspend(self):
        """ Suspend this service, but maintain the state """
        return state
    
    def terminate(self):
        """ Ends this service"""
