class {{service.class}}:
    """ {{service.class}}
        Provides an implementation of the {{service.name}} service
        Generated by {{generator}} at {{date}} by {{username}}
    
        NOTE: This file is generated as a stub, and has to be implemented by the user. Re-running the codegen plugin 
        will not change the contents of this file.
     
        Template by TNO, 2017 """
         
    def resume_from(self, state):
        """ Resume this service from a previous state 
            Auto-generated method stub """

    def configure(self, config):
        """ Configure this service with the provided config 
            Auto-generated method stub """

    def modify(self, config):
        """ Modify the configuration with the provided config 
            Auto-generated method stub """

    def suspend(self):
        """ Suspend this service, but maintain the state 
            Auto-generated method stub """
        return self._state

    def terminate(self):
        """ Ends this service 
            Auto-generated method stub """
