# Gitlab CI definition for def-pi
#
# This file is based on the official docker maven template
#
# author: C.J. van Leeuwen
# since: 2-6-2017

variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.repo.local=/cache/maven.repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

image: maven:3.5.0-jdk-8

stages:
  - build
  - test
  - integrate
  - deploy

cache:
  paths:
    - /cache/maven.repository
 
# Validate merge requests using JDK8
java-compile:
  except:
    - deploy
    - master
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml clean test-compile'

# Verify merge requests using JDK8
java-test:
  stage: test
  except:
    - master
    - deploy
  script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml test'

.plugin_template: &plugin
  stage: test
  except:
    - master
    - deploy
  before_script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml install -pl ../maven-plugin -am -DskipTests'
  script:
    - 'mvn $MAVEN_CLI_OPTS -f $TEST_PROJ/pom.xml -P codegen generate-sources'

#Test plugin on xsd
plugin-test:proto:
  variables:
    TEST_PROJ: skeleton_proto
  <<: *plugin

#Test plugin on xsd
plugin-test:xsd:
  variables:
    TEST_PROJ: skeleton_xsd
  <<: *plugin

#Deploy to artifactory and registry
integrate:master:
  only:
    - master
    - defpici
  stage: integrate
  script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml deploy'

integrate:ui:
  image: docker:17.03.2-ce-git
  only:
    - master
    - defpici
  stage: integrate
  script:
    - 'docker build orchestrator-ui -t def-pi1.sensorlab.tno.nl:5000/defpi/orchestrator-ui'
    - 'docker push def-pi1.sensorlab.tno.nl:5000/defpi/orchestrator-ui'

.integrate_template: &integrate_service
  only:
    - master
    - defpici
  stage: deploy
  before_script:  
    - 'mvn $MAVEN_CLI_OPTS -f $TEST_PROJ/pom.xml -P codegen generate-sources'
  script:
    - 'mvn $MAVEN_CLI_OPTS -f $TEST_PROJ/pom.xml clean deploy'

integrate:skeleton_proto:
  variables:
    TEST_PROJ: skeleton_proto
  <<: *integrate_service 

integrate:xsd_proto:
  variables:
    TEST_PROJ: skeleton_xsd
  <<: *integrate_service

# And finally run service on def-pi1
deploy:orchestrator:
  image: tmaier/docker-compose:17.06
  tags:
    - defpi1
  only:
    - master
    - deploy
  stage: deploy
  script:
    - 'docker-compose -p def-pi -f orchestrator/docker-compose.yml up -d'
