# Gitlab CI definition for def-pi
#
# This file is based on the official docker maven template
#
# author: C.J. van Leeuwen
# since: 2-6-2017

variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.repo.local=/cache/maven.repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

image: maven:3.5.0-jdk-8

stages:
  - build
  - test
  - integrate
  - deploy

cache:
  paths:
    - /cache/maven.repository
 
# Validate java code using JDK8; for master this is a sanity check
java-compile:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml clean test-compile'

# Run Junit tests with maven; not on master where we will deploy
java-test:
  stage: test
  except:
    - master
  script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml test'

# Plugin template, how test the plugins with the code generator; on master we deploy
.plugin_template: &plugin
  stage: test
  except:
    - master
  before_script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml install -pl ../maven-plugin -am -DskipTests'
  script:
    - 'mvn $MAVEN_CLI_OPTS -f $TEST_PROJ/pom.xml -P codegen generate-sources'

# Test plugin on xsd
plugin-test:proto:
  variables:
    TEST_PROJ: skeleton_proto
  <<: *plugin

# Test plugin on xsd
plugin-test:xsd:
  variables:
    TEST_PROJ: skeleton_xsd
  <<: *plugin

# Deploy the complete project with modules to artifactory and the orchestrator to registry
integrate:master:
  only:
    - master
    - defpici
  stage: integrate
  script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml deploy'

# Deploy UI to registry
integrate:ui:
  image: docker:17.03.2-ce-git
  only:
    - master
    - defpici
  stage: integrate
  script:
    - 'docker build orchestrator-ui -t def-pi1.sensorlab.tno.nl:5000/defpi/orchestrator-ui'
    - 'docker push def-pi1.sensorlab.tno.nl:5000/defpi/orchestrator-ui'

# How to deploy the (test)services to the registry
.integrate_template: &integrate_service
  only:
    - master
    - defpici
  stage: deploy
  before_script:
    # In this stage the plugin should be available from artifactory
    - 'mvn $MAVEN_CLI_OPTS -f $TEST_PROJ/pom.xml -P codegen generate-sources'
  script:
    - 'mvn $MAVEN_CLI_OPTS -f $TEST_PROJ/pom.xml clean deploy'

# Deploy the proto skeleton
integrate:skeleton_proto:
  variables:
    TEST_PROJ: skeleton_proto
  <<: *integrate_service 

# Deploy the XSD skeleton    
integrate:xsd_proto:
  variables:
    TEST_PROJ: skeleton_xsd
  <<: *integrate_service

# And finally run the orchestrator on def-pi1 using docker-compose
deploy:orchestrator:
  image: tmaier/docker-compose:17.06
  tags:
    - defpi1
  only:
    - master
  stage: deploy
  script:
    - 'docker-compose -f orchestrator/docker-compose.yml pull'
    - 'docker-compose -p def-pi -f orchestrator/docker-compose.yml up -d'
