# Gitlab CI definition for def-pi
#
# This file is based on the official docker maven template
#
# author: C.J. van Leeuwen
# since: 2-6-2017

variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.repo.local=/cache/maven.repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

image: maven:3.5.0-jdk-8

stages:
  - build
  - test
  - plugintest
  - deploy

cache:
  paths:
    - /cache/maven.repository
 
# Validate merge requests using JDK8
validate:jdk8:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml clean test-compile'

# Verify merge requests using JDK8
verify:jdk8:
  stage: test
  except:
    - master
  script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml test'

.plugin_template: &plugin
  stage: plugintest
  except:
    - master
  before_script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml install -pl ../maven-plugin -am -DskipTests'
  script:
    - 'mvn $MAVEN_CLI_OPTS -f $TEST_PROJ/pom.xml -P codegen generate-sources'
  artifacts:
    expire_in: 1 week
    paths:
      - "$TEST_PROJ/src"

#Test plugin on xsd
test-compile:proto:
  variables:
    TEST_PROJ: skeleton_proto
  <<: *plugin

#Test plugin on xsd
test-xsd-compile:
  variables:
    TEST_PROJ: skeleton_xsd
  <<: *plugin

#Finally deploy stuff
.deploy_template: &deploy
  stage: deploy
  only:
    - master
    - defpici

deploy:master:
  <<: *deploy 
  script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml deploy'

deploy:skeleton_proto:
  <<: *deploy 
  script:
    - 'mvn $MAVEN_CLI_OPTS -f skeleton_proto/pom.xml deploy'
  dependencies:
    - test-compile:proto

deploy:xsd_proto:
  <<: *deploy 
  script:
    - 'mvn $MAVEN_CLI_OPTS -f skeleton_xsd/pom.xml deploy'
  dependencies:
    - test-compile:xsd
