# Gitlab CI definition for def-pi
#
# This file is based on the official docker maven template
#
# author: C.J. van Leeuwen
# since: 2-6-2017

variables:
  # This will supress any download for dependencies and plugins or upload messages which would clutter the console log.
  # `showDateTime` will show the passed time in milliseconds. You need to specify `--batch-mode` to make this work.
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.repo.local=./cache/maven.repository"
  # As of Maven 3.3.0 instead of this you may define these options in `.mvn/maven.config` so the same config is used
  # when running from the command line.
  # `installAtEnd` and `deployAtEnd`are only effective with recent version of the corresponding plugins.
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true -f master/pom.xml"

cache:
  paths:
    - ./cache/maven.repository
 
# Validate merge requests using JDK8
validate:jdk8:
  image: maven:3.3.9-jdk-8
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS test-compile'

# Verify merge requests using JDK8
verify:jdk8:
  image: maven:3.3.9-jdk-8
  stage: test
  script:
    - 'mvn $MAVEN_CLI_OPTS verify'

#deploy:jdk8:
#  image: maven:3.3.9-jdk-8
#  stage: deploy
#  only:
#    - master
#  script:
#    - 'mvn $MAVEN_CLI_OPTS deploy'
