# Gitlab CI definition for def-pi
#
# This file is based on the official docker maven template
#
# author: C.J. van Leeuwen
# since: 2-6-2017

variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.repo.local=./cache/maven.repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

image: maven:3.3.9-jdk-8

stages:
  - build
  - test
  - plugintest
  - deploy

cache:
  untracked: true
  key: "$CI_COMMIT_REF_NAME"
  paths:
    - ./cache/maven.repository
 
# Validate merge requests using JDK8
validate:jdk8:
  stage: build
  artifacts:
    paths:
      - ./*/target
  script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml test-compile'

# Verify merge requests using JDK8
verify:jdk8:
  stage: test
  except:
    - master
  script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml test'

# Install modules for next steps (we need to test the plugin)
install-plugin:
  stage: test
  artifacts:
    paths:
      - ./*/target
  except:
    - master
  script:
    - 'mvn $MAVEN_CLI_OPTS -DskipTests -f master/pom.xml install'

#Test plugin on protobuf
test-proto-compile:
  stage: plugintest
  artifacts:
    paths:
      - skeleton_proto/*
  except:
    - master
  script:
    - 'mvn $MAVEN_CLI_OPTS -f skeleton_proto/pom.xml -P codegen generate-sources'

#Test plugin on xsd
test-xsd-compile:
  stage: plugintest
  artifacts:
    paths:
      - skeleton_xsd/*
  except:
    - master
  script:
    - 'mvn $MAVEN_CLI_OPTS -f skeleton_xsd/pom.xml -P codegen generate-sources'

#Finally deploy stuff
deploy:
  stage: deploy
  only:
    - master
  script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml clean deploy'

deploy-proto-skeleton:
  stage: deploy
  only:
    - master
  script:
    - 'mvn $MAVEN_CLI_OPTS -f skeleton_proto/pom.xml deploy'

deploy-xsd-skeleton:
  stage: deploy
  only:
    - master
  script:
    - 'mvn $MAVEN_CLI_OPTS -f skeleton_xsd/pom.xml deploy'
