# Gitlab CI definition for def-pi
#
# This file is based on the official docker maven template
#
# author: C.J. van Leeuwen
# since: 2-6-2017

variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.repo.local=cache/maven.repository -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
  MAVEN_CLI_OPTS: "-T 4 --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"
  JDK_8_IMAGE: maven:3.5.3-jdk-8-slim
  JDK_10_IMAGE: maven:3.5.3-jdk-10-slim
  DOCKER_IMAGE: docker:18.04.0-ce-git
  BUSYBOX_IMAGE: busybox:latest

stages:
  - build
  - test
  - predeploy
  - deploy

# Validate branch make sure we don't merge ek2 into master
branch-test:ek2:
  stage: build
  only:
    - ek2_ui
  image: $BUSYBOX_IMAGE
  script:
    - "grep ek2 dashboard/pom.xml"
    - "grep ek2 dashboard-gateway/pom.xml"

branch-test:other:
  stage: build
  except:
    - ek2_ui
  image: $BUSYBOX_IMAGE
  script:
    - "! grep ek2 dashboard/pom.xml"
    - "! grep ek2 dashboard-gateway/pom.xml"

# Validate java code; usually this is a sanity check
.java-compile: &compile
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml clean test-compile'
  cache:
    paths:
      - cache/maven.repository

java-compile:jdk8:
    <<: *compile
    image: $JDK_8_IMAGE

java-compile:jdk10:
    <<: *compile
    image: $JDK_10_IMAGE

# Compile the orchestrator-ui
ui-compile:
  image: $DOCKER_IMAGE
  stage: build
  script:
    - 'docker build orchestrator-ui'

# *** TEST JOBS *** #

# Run Junit tests with maven; not on master where we will deploy
.java-test: &test
  stage: test
  except:
    - master
  script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml package'
  cache:
    paths:
      - cache/maven.repository

java-test:jdk8:
    <<: *test
    image: $JDK_8_IMAGE

java-test:jdk10:
    <<: *test
    image: $JDK_10_IMAGE

# *** predeployMENT JOBS *** #

# Deploy the complete project with modules to artifactory and the orchestrator to registry
java-deploy:
  stage: predeploy
  only:
    - master
    - defpici
  image: $JDK_10_IMAGE
  script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml deploy -Ddocker.registry=defpi.hesilab.nl:5000'
  cache:
    paths:
      - cache/maven.repository

# Deploy UI to registry
ui-deploy:
  stage: predeploy
  only:
    - master
    - defpici
  image: $DOCKER_IMAGE
  before_script:  
    - 'docker build orchestrator-ui -t defpi.hesilab.nl:5000/defpi/orchestrator-ui'
  script:
    - 'docker push defpi.hesilab.nl:5000/defpi/orchestrator-ui'

# *** FINAL DEPLOY JOBS *** #

# And finally run the orchestrator on hesilab using docker-compose
deploy-compose:
  stage: deploy
  tags:
    - hesilab
  only:
    - master
  image: tmaier/docker-compose:18.09
  before_script:
    - 'docker-compose -f orchestrator/docker-compose.test.yml pull'
  script:
    - 'docker-compose -f orchestrator/docker-compose.test.yml up -d'

