# Gitlab CI definition for def-pi
#
# This file is based on the official docker maven template
#
# author: C.J. van Leeuwen
# since: 2-6-2017

variables:
  MAVEN_OPTS: "-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.repo.local=cache/maven.repository -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
  MAVEN_CLI_OPTS: "-T 4 --batch-mode --errors --fail-at-end --show-version -DinstallAtEnd=true -DdeployAtEnd=true"

image: maven:3.5.3-jdk-10

stages:
  - build
  - test
  - predeploy
  - deploy

# Validate branch make sure we don't merge ek2 into master
branch-test:ek2:
  stage: build
  only:
    - ek2_ui
  script:
    - "grep ek2 dashboard/pom.xml"
    - "grep ek2 dashboard-gateway/pom.xml"

branch-test:other:
  stage: build
  except:
    - ek2_ui
  script:
    - "! grep ek2 dashboard/pom.xml"
    - "! grep ek2 dashboard-gateway/pom.xml"

# Validate java code using JDK8; for master this is a sanity check
java-compile:
  stage: build
  script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml clean test-compile'
  cache:
    paths:
      - cache/maven.repository

# *** BUILD JOBS *** #

ui-compile:
  image: docker:18.04.0-ce-git
  stage: build
  script:
    - 'docker build orchestrator-ui'

# *** TEST JOBS *** #

# Run Junit tests with maven; not on master where we will deploy
java-test:
  stage: test
  except:
    - master
  script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml test'
  cache:
    paths:
      - cache/maven.repository

# Test to see if the orchestrator ui does what it is supposed to
#ui-test:
#  image: docker:17.03.2-ce-git
#  tags:
#    - defpi2
#  stage: test
#  except:
#    - master
#  before_script:
#    - 'docker build orchestrator-ui -t orchestrator-ui:test'
#    - 'docker run --rm --name ui-test -d -p 8756:80 orchestrator-ui:test'
#    - 'sleep 10'
#  script:
#    - 'wget -q localhost:8756/login.html -O -| grep "Orchestrator"'
#  after_script:
#    - 'docker stop ui-test'

# *** predeployMENT JOBS *** #

# Deploy the complete project with modules to artifactory and the orchestrator to registry
java-deploy:
  stage: predeploy
  only:
    - master
    - defpici
  script:
    - 'mvn $MAVEN_CLI_OPTS -f master/pom.xml deploy -Ddocker.registry=defpi.hesilab.nl:5000'
  cache:
    paths:
      - cache/maven.repository

# Deploy UI to registry
ui-deploy:
  image: docker:18.04.0-ce-git
  stage: predeploy
  only:
    - master
    - defpici
  before_script:  
    - 'docker build orchestrator-ui -t defpi.hesilab.nl:5000/defpi/orchestrator-ui'
  script:
    - 'docker push defpi.hesilab.nl:5000/defpi/orchestrator-ui'

# Test the deployment first
# test-deploy:
#  image: tmaier/docker-compose:17.06
#  tags:
#    - defpi2
#  only:
#    - master
#    - defpici
#  stage: predeploy
#  before_script:
#    - 'docker-compose -p test -f orchestrator/docker-compose.test.yml pull'
#    - 'docker-compose -p test -f orchestrator/docker-compose.test.yml up -d'
#    - 'sleep 120'
#  script:
#    - 'nc -zv def-pi2.sensorlab.tno.nl:9999'
#    - 'wget -q def-pi2.sensorlab.tno.nl:84/login.html -O - | grep "Orchestrator"'
#    - 'wget -q def-pi2.sensorlab.tno.nl:8484/swagger.json -O - | grep "dEF-Pi API"'
#  after_script:
#    - 'docker-compose -p test -f orchestrator/docker-compose.test.yml down'

# *** FINAL DEPLOY JOBS *** #

# And finally run the orchestrator on hesilab using docker-compose
deploy-compose:
  image: tmaier/docker-compose:18.02
  stage: deploy
  tags:
    - hesilab
  only:
    - master
  before_script:
    - 'docker-compose -f orchestrator/docker-compose.test.yml pull'
  script:
    - 'docker-compose -f orchestrator/docker-compose.test.yml up -d'

