package org.flexiblepower.defpi.dashboard.gateway.http;

import javax.annotation.Generated;

import org.flexiblepower.defpi.dashboard.gateway.GatewayConnectionManagerImpl;
import org.flexiblepower.defpi.dashboard.gateway.http.proto.Gateway_httpProto.HTTPRequest;
import org.flexiblepower.defpi.dashboard.gateway.http.proto.Gateway_httpProto.HTTPResponse;
import org.flexiblepower.serializers.ProtobufMessageSerializer;
import org.flexiblepower.service.ConnectionHandler;
import org.flexiblepower.service.InterfaceInfo;

/**
 * Gateway_httpConnectionHandler
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
 * Template by TNO, 2017
 * 
 * @author wilco
 */
@Generated(value = "org.flexiblepower.plugin.servicegen", date = "Oct 26, 2017 12:58:33 PM")
@InterfaceInfo(name = "gateway", version = "HTTP", 
		receivesHash = "c46d5961b42774f80194e8308e4a1bec450881925f8d20a08a1f764acf22ed24", 
		sendsHash = "aafa92f5e8c919cc004f017d0c7706bf5e72594e656cf04cd67dd47b97cf7c6c",
		manager = GatewayConnectionManagerImpl.class,
		serializer = ProtobufMessageSerializer.class, 
		receiveTypes = { HTTPRequest.class }, sendTypes = { HTTPResponse.class })
public interface Gateway_httpConnectionHandler extends ConnectionHandler {

	public void handleHTTPRequestMessage(HTTPRequest message);

}