package org.flexiblepower.defpi.dashboard.gateway.http;

import javax.annotation.Generated;

import org.flexiblepower.defpi.dashboard.Dashboard;
import org.flexiblepower.defpi.dashboard.gateway.http.proto.Gateway_httpProto.HTTPRequest;
import org.flexiblepower.service.Connection;

/**
 * Gateway_httpConnectionHandlerImpl
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. NOTE: This
 * file is generated as a stub, and has to be implemented by the user.
 * Re-running the codegen plugin will not change the contents of this file.
 * Template by TNO, 2017
 * 
 * @author wilco
 */
@Generated(value = "org.flexiblepower.plugin.servicegen", date = "Oct 26, 2017 12:58:33 PM")
public class Gateway_httpConnectionHandlerImpl implements Gateway_httpConnectionHandler {

	private final Connection connection;

	private final Dashboard service;

	/**
	 * Auto-generated constructor for the ConnectionHandlers of the provided service
	 *
	 * @param service
	 *            The service for which to handle the connections
	 */
	public Gateway_httpConnectionHandlerImpl(Connection connection, Dashboard service) {
		this.connection = connection;
		this.service = service;
	}

	@Override
	public void handleHTTPRequestMessage(HTTPRequest message) {
		connection.send(service.getRequestRouter().handle(message));
	}

	@Override
	public void onSuspend() {
		// TODO Auto-generated method stub

	}

	@Override
	public void resumeAfterSuspend() {
		// TODO Auto-generated method stub

	}

	@Override
	public void onInterrupt() {
		// TODO Auto-generated method stub

	}

	@Override
	public void resumeAfterInterrupt() {
		// TODO Auto-generated method stub

	}

	@Override
	public void terminated() {
		// TODO Auto-generated method stub

	}

}