orchestrator:
  image: def-pi1.sensorlab.tno.nl:5000/defpi/orchestrator:0.1.1-SNAPSHOT
  ports:
    - 0.0.0.0:8080:8080
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock
  links:
    - mongo
  environment:
    - MONGO_HOST=mongo
    - MONGO_DATABASE=def-pi
    - MONGO_PORT=27017
    - REGISTRY_URL=def-pi1.sensorlab.tno.nl
mongo:
  image: mongo
orchestrator-ui:
  image: def-pi1.sensorlab.tno.nl:5000/defpi/orchestrator-ui
  ports:
    - 0.0.0.0:8081:80
  environment:
    - ORCHESTARTOR_URL=http://def-pi1.sensorlab.tno.nl:8080/
