version: "3"
networks:
  management:
    driver: overlay
services:
  orchestrator:
    image: defpi.heislab.nl:5000/defpi/orchestrator
    ports:
      - 0.0.0.0:8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - mongo
    networks:
      - management
    environment:
      - MONGO_HOST=mongo
      - MONGO_DATABASE=def-pi
      - MONGO_PORT=27017
      - REGISTRY_URL=defpi.hesilab.nl:5000
  orchestrator-ui:
    image: defpi.hesilab.nl:5000/defpi/orchestrator-ui
    ports:
      - 80:80
    environment:
      - ORCHESTRATOR_URL=http://def-pi1.sensorlab.tno.nl:8080/
  mongo:
    image: mvertes/alpine-mongo
    networks:
      - management
