# This is the test environment, which is deployed automatically during CI/CD pipeline.

version: "3"
networks:
  management:
    driver: overlay
services:
  orchestrator:
    image: ci.hesi.energy:5000/defpi/orchestrator:latest
    restart: always
    ports:
      - 0.0.0.0:8080:8080
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - mongo
    networks:
      - management
    environment:
      - MONGO_HOST=mongo
      - MONGO_DATABASE=def-pi
      - MONGO_PORT=27017
      - REGISTRY_URL=defpi.hesilab.nl:5000
  orchestrator-ui:
    image: ci.hesi.energy:5000/defpi/orchestrator-ui:latest
    restart: always
    ports:
      - 0.0.0.0:84:80
    environment:
      - ORCHESTRATOR_URL=http://defpi.hesi.tno.nl.nl:8080/
  mongo:
    image: mvertes/alpine-mongo
    restart: always
    volumes:
      - /srv/mongo/db:/data/db
    ports:
      - 0.0.0.0:27017:27017
    networks:
      - management
