version: "3"
networks:
  management:
    driver: overlay
services:
  orchestrator:
    image: def-pi1.sensorlab.tno.nl:5000/defpi/orchestrator:0.2.1-SNAPSHOT
    ports:
      - 8484:8080
      - 9999:9999
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    links:
      - mongo_test
    networks:
      - management
    environment:
      - JVM_ARGUMENTS=-Xdebug -agentlib:jdwp=transport=dt_socket,address=9999,server=y,suspend=n
      - MONGO_HOST=mongo_test
      - MONGO_DATABASE=def-pi
      - MONGO_PORT=27017
      - REGISTRY_URL=def-pi1.sensorlab.tno.nl:5000
  orchestrator-ui:
    image: def-pi1.sensorlab.tno.nl:5000/defpi/orchestrator-ui
    ports:
      - 84:80
    environment:
      - ORCHESTRATOR_URL=http://localhost:8484/
  mongo_test:
    image: mvertes/alpine-mongo
    ports:
      - 0.0.0.0:27017:27017
    networks:
      - management
