package {{service.package}};

import javax.annotation.Generated;

/**
 * {{config.interface}} provides the interface for the {{service.name}} service
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
 * Template by TNO, 2017
 * 
 * @author {{username}}
 */
 @Generated(value = "{{generator}}", date = "{{date}}")
public interface {{config.interface}} {

{{config.definitions}}

}