package {{service.package}};

import javax.annotation.Generated;
{{config.imports}}
/**
 * {{config.interface}} provides the configuration interface for the {{service.name}} service.
 * This configuration interface corresponds with the parameters as set in the service.json file used to generate this
 * file.
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
 * Template by FAN, 2019
 * 
 * @author {{username}}
 */
@Generated(value = "{{generator}}", date = "{{date}}")
public interface {{config.interface}} {

{{config.definitions}}

}