package {{package}}.{{itf.packagename}};

import javax.annotation.Generated;

{{handler.imports}}
import org.flexiblepower.serializers.{{itf.serializer}};
import org.flexiblepower.service.ConnectionHandler;
import org.flexiblepower.service.InterfaceInfo;

/**
 * {{handler.class}}
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
 * Template by TNO, 2017
 * 
 * @author {{username}}
 */
@Generated(value = "{{generator}}", date = "{{date}}")
@InterfaceInfo(name = "{{itf.name}}", version = "{{itf.version}}", 
		receivesHash = "{{itf.receivesHash}}", 
		sendsHash = "{{itf.sendsHash}}",
		factory = {{factory.class}}.class,
		serializer = {{itf.serializer}}.class, 
		receiveTypes = { {{itf.receiveClasses}} }, sendTypes = { {{itf.sendClasses}} })
public interface {{handler.class}} extends ConnectionHandler {

{{handlers}}

}