// File generated by org.flexiblepower.create-service-maven-plugin
// Template by: leeuwencjv, TNO, 2017

package {{package}}.{{itf.packagename}};

import javax.annotation.Generated;

{{handler.imports}}
import org.flexiblepower.service.ConnectionHandler;
import org.flexiblepower.service.InterfaceInfo;
import org.flexiblepower.service.serializers.{{itf.serializer}};

/**
 * {{handler.class}}
 * 
 * @author {{username}}
 * @version {{itf.version}}
 * @since {{date}}
 */
@Generated("{{generator}}")
@InterfaceInfo(name = "{{itf.name}}", version = "{{itf.version}}", 
		receivesHash = "{{itf.receivesHash}}", 
		sendsHash = "{{itf.sendsHash}}", 
		serializer = {{itf.serializer}}.class, 
		receiveTypes = { {{itf.receiveClasses}} }, sendTypes = { {{itf.sendClasses}} })
public interface {{handler.class}} extends ConnectionHandler {

{{handlers}}

}