package {{service.package}}.{{vitf.package}};

import javax.annotation.Generated;

{{vitf.handler.interface.imports}}
import org.flexiblepower.serializers.{{vitf.serializer}};
import org.flexiblepower.service.ConnectionHandler;
import org.flexiblepower.service.InterfaceInfo;

/**
 * Interface for connection handlers that will handle messages on the {{itf.name}} interface.
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
 * Template by FAN, 2017
 * 
 * @author {{username}}
 */
@Generated(value = "{{generator}}", date = "{{date}}")
@InterfaceInfo(name = "{{itf.name}}", version = "{{vitf.version}}", 
		receivesHash = "{{vitf.receivesHash}}", 
		sendsHash = "{{vitf.sendsHash}}",
		serializer = {{vitf.serializer}}.class, 
		receiveTypes = { {{vitf.receiveClasses}} }, sendTypes = { {{vitf.sendClasses}} })
public interface {{vitf.handler.interface}} extends ConnectionHandler {

{{vitf.handler.definitions}}

}