// File generated by org.flexiblepower.create-service-maven-plugin
// Template by: leeuwencjv, TNO, 2017

package {{package}}.{{itf.packagename}};

import javax.annotation.Generated;

{{handler.imports}}
import org.flexiblepower.service.Connection;

/**
 * {{handlerImpl.class}}
 * 
 * @author {{username}}
 * @version {{itf.version}}
 * @since {{date}}
 */
@Generated("{{generator}}")
public class {{handlerImpl.class}} implements {{handler.class}} {

{{handlerImpls}}

	@Override
	public void onConnected(Connection connection) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void onSuspend() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void resumeAfterSuspend() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void onInterrupt() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void resumeAfterInterrupt() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void terminated() {
		// TODO Auto-generated method stub
		
	}

}