// File generated by org.flexiblepower.create-service-maven-plugin
// Template by: leeuwencjv, TNO, 2017

package {{package}}.handlers;

import org.flexiblepower.service.Connection;
import {{package}}.handlers.{{handler.class}};
{{handler.imports}}

import javax.annotation.Generated;


/**
 * {{handlerImpl.class}}
 * 
 * @author {{username}}
 * @version {{itf.version}}
 * @since {{date}}
 */
 @Generated({{generator}})
public class {{handlerImpl.class}} implements {{handler.class}} {

	{{handlerImpls}}

	@Override
	public void onConnected(Connection connection) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void onSuspend() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void resumeAfterSuspend() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void onInterrupt() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void resumeAfterInterrupt() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void terminated() {
		// TODO Auto-generated method stub
		
	}

}