package {{package}}.{{itf.packagename}};

import javax.annotation.Generated;

import {{package}}.{{service.class}};
{{handler.imports}}
import org.flexiblepower.service.Connection;

/**
 * {{handlerImpl.class}}
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file is generated as a stub, and has to be implemented by the user. Re-running the codegen plugin will
 * 		 not change the contents of this file.
 * Template by TNO, 2017
 * 
 * @author {{username}}
 */
@Generated(value = "{{generator}}", date = "{{date}}")
public class {{handlerImpl.class}} implements {{handler.class}} {

	private final {{service.class}} service;

	/**
	 * Auto-generated constructor for the ConnectionHandlers of the provided service
	 *
	 * @param service The service for which to handle the connections
	 */
	{{handlerImpl.class}}({{service.class}} service) {
		this.service = service;
	}

{{handlerImpls}}

	@Override
	public void onConnected(Connection connection) {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void onSuspend() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void resumeAfterSuspend() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void onInterrupt() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void resumeAfterInterrupt() {
		// TODO Auto-generated method stub
		
	}

	@Override
	public void terminated() {
		// TODO Auto-generated method stub
		
	}

}