# File generated by org.flexiblepower.create-service-maven-plugin
# Template by: leeuwencjv, TNO, 2017

FROM {{from}}

ADD ${project.artifactId}-${project.version}-jar-with-dependencies.jar /

LABEL org.flexiblepower.serviceName="{{service.name}}" 
LABEL org.flexiblepower.interfaces='{{interfaces}}' 

ENTRYPOINT ["java", "-jar", "/${project.artifactId}-${project.version}-jar-with-dependencies.jar"]