# File generated by org.flexiblepower.create-service-maven-plugin
# NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
# Template by FAN, 2017

FROM {{from}}

COPY ${project.artifactId}-${project.version}-jar-with-dependencies.jar defpi-resources/* /

LABEL org.flexiblepower.serviceName="{{service.name}}" 
LABEL org.flexiblepower.parameters='{{parameters}}'
LABEL org.flexiblepower.interfaces='{{interfaces}}'

ENTRYPOINT {{entrypoint}}