# File generated by org.flexiblepower.create-service-maven-plugin
# NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
# Template by TNO, 2017

FROM {{from}}

ADD ${project.artifactId}-${project.version}-jar-with-dependencies.jar /

LABEL org.flexiblepower.serviceName="{{service.name}}" 
LABEL org.flexiblepower.interfaces='{{interfaces}}' 

ENTRYPOINT ["java", "-jar", "/${project.artifactId}-${project.version}-jar-with-dependencies.jar"]