package {{package}}.{{itf.packagename}};

import javax.annotation.Generated;

import {{package}}.{{service.class}};
import org.flexiblepower.service.ConnectionHandler;
import org.flexiblepower.service.ConnectionHandlerFactory;

/**
 * {{factory.class}}
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
 * Template by TNO, 2017
 * 
 * @author {{username}}
 */
@Generated(value = "{{generator}}", date = "{{date}}")
public class {{factory.class}} implements ConnectionHandlerFactory {

	private final {{service.class}} service;
	
	/**
	 * Auto-generated constructor building the factory for ConnectionHandlers of the provided service
	 *
	 * @param service The service that will be used as argument to instantiate the ConnectionHandlers
	 */
	public {{factory.class}}({{service.class}} service) {
		this.service = service;
	}

	@Override
	public ConnectionHandler build() {
		return new {{handlerImpl.class}}(this.service);
	}

}

