package {{service.package}}.{{itf.package}};

import javax.annotation.Generated;

{{itf.manager.imports.interface}}
import org.flexiblepower.service.Connection;
import org.flexiblepower.service.ConnectionHandlerManager;

/**
 * {{itf.manager.class}}
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file is generated as a stub, and has to be implemented by the user. Re-running the codegen plugin will
 * 		 not change the contents of this file.
 * Template by TNO, 2017
 * 
 * @author {{username}}
 */
@Generated(value = "{{generator}}", date = "{{date}}")
public interface {{itf.manager.interface}} extends ConnectionHandlerManager {

{{itf.manager.definitions}}

}

