package {{service.package}}.{{itf.package}};

import javax.annotation.Generated;

{{itf.manager.imports.interface}}
import org.flexiblepower.service.Connection;
import org.flexiblepower.service.ConnectionHandlerManager;

/**
 * Interface for the connection handler manager.
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
 * Template by FAN, 2019
 * 
 * @author {{username}}
 */
@Generated(value = "{{generator}}", date = "{{date}}")
public interface {{itf.manager.interface}} extends ConnectionHandlerManager {

{{itf.manager.definitions}}

}

