	/**
	 * This is a default implementation providing a RAML proxy client of the type
	 * {{resource.type}} for this interface. By default it is generated by the RamlProxyClient,
	 * but it may be overriden if required
	 * 
	 * @return A {{resource.type}} proxy that will send requests for this interface
	 */
	public default {{resource.type}} get{{resource.type}}() {
		return RamlProxyClient.generateClient({{resource.type}}.class, this);
	}