package org.flexiblepower.defpi.dashboardgateway.dashboard;

import javax.annotation.Generated;

import org.flexiblepower.defpi.dashboardgateway.DashboardGateway;
import org.flexiblepower.defpi.dashboardgateway.dashboard.http.Dashboard_httpConnectionHandler;
import org.flexiblepower.defpi.dashboardgateway.dashboard.http.Dashboard_httpConnectionHandlerImpl;
import org.flexiblepower.service.Connection;

/**
 * DashboardConnectionManagerImpl
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file is generated as a stub, and has to be implemented by the user. Re-running the codegen plugin will
 * 		 not change the contents of this file.
 * Template by FAN, 2017
 * 
 */
@Generated(value = "org.flexiblepower.plugin.servicegen", date = "Oct 9, 2017 8:45:27 PM")
public class DashboardConnectionManagerImpl implements DashboardConnectionManager {

	private final DashboardGateway service;
	
	/**
	 * Auto-generated constructor building the factory for ConnectionHandlers of the provided service
	 *
	 * @param service The service that will be used as argument to instantiate the ConnectionHandlers
	 */
	public DashboardConnectionManagerImpl(DashboardGateway service) {
		this.service = service;
	}

	@Override
	public Dashboard_httpConnectionHandler buildHttp(Connection connection) {
		return new Dashboard_httpConnectionHandlerImpl(connection, this.service);
	}

}

