package org.flexiblepower.defpi.dashboardgateway.dashboard;

import javax.annotation.Generated;

import org.flexiblepower.defpi.dashboardgateway.dashboard.http.Dashboard_httpConnectionHandler;
import org.flexiblepower.service.Connection;
import org.flexiblepower.service.ConnectionHandlerManager;

/**
 * DashboardConnectionManagerImpl
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
 * Template by TNO, 2017
 * 
 * @author wilco
 */
@Generated(value = "org.flexiblepower.plugin.servicegen", date = "Oct 23, 2017 7:55:29 PM")
public interface DashboardConnectionManager extends ConnectionHandlerManager {

	public Dashboard_httpConnectionHandler buildHttp(Connection connection);

}

