name: 'PV Panel Simulation'
descriptors:
  HTTP:
    file: 'HTTP.proto'
    source: 'protobuf'
  EFI:
    file: 'efi.xsd'
    source: 'xsd'
interfaces:
  - name: 'Widget'
    classPrefix: 'Widget'
    autoConnect: true
    cardinality: 1
    subscribe:
     - descriptor: HTTP
       type: HTTPRequest
    publish: 
     - descriptor: HTTP
       type: HTTPResponse
  - name: 'Efi'
    classPrefix: 'Efi'
    autoConnect: true
    cardinality: 1
    subscribe:
     - descriptor: EFI
       type: CurtailmentAllocation
     - descriptor: EFI
       type: AllocationRevoke
    publish:
     - descriptor: EFI
       type: InflexibleRegistration
     - descriptor: EFI
       type: InflexibleUpdate
     - descriptor: EFI
       type: AllocationStatusUpdate
     - descriptor: EFI
       type: ControlSpaceRevoke