package org.flexiblepower.defpi.dashboardgateway;

import java.io.Serializable;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;

import javax.annotation.Generated;

import org.eclipse.jetty.server.Server;
import org.flexiblepower.defpi.dashboardgateway.dashboard.http.Dashboard_httpConnectionHandlerImpl;
import org.flexiblepower.service.Service;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

/**
 * DashboardGateway provides an implementation of the Dashboard Gateway service
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. NOTE: This
 * file is generated as a stub, and has to be implemented by the user.
 * Re-running the codegen plugin will not change the contents of this file.
 * Template by TNO, 2017
 * 
 * @author wilco
 */
@Generated(value = "org.flexiblepower.plugin.servicegen", date = "Oct 9, 2017 8:45:27 PM")
public class DashboardGateway implements Service<DashboardGatewayConfiguration> {

	public static final Logger LOG = LoggerFactory.getLogger(DashboardGateway.class);

	private Server server;
	private Map<String, Dashboard_httpConnectionHandlerImpl> dashboardConnections = Collections
			.synchronizedMap(new HashMap<>());

	@Override
	public void resumeFrom(Serializable state) {
		// TODO Auto-generated method stub

	}

	@Override
	public void init(DashboardGatewayConfiguration config) {
		try {
			server = new Server(8080);
			server.setHandler(new GatewayHandler(this));
			server.start();
		} catch (Exception e) {
			LOG.error("Could not start DashboardGateway HTTP server", e);
		}
	}

	@Override
	public void modify(DashboardGatewayConfiguration config) {
		// TODO Auto-generated method stub
	}

	@Override
	public Serializable suspend() {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public void terminate() {
		try {
			server.stop();
		} catch (Exception e) {
			LOG.error("Could not stop DashboardGateway HTTP server", e);
		}
	}

	public void addDashboardConnection(Dashboard_httpConnectionHandlerImpl connection) {
		this.dashboardConnections.put(connection.getUserEmail(), connection);
	}

	public void removeDashboardConnection(Dashboard_httpConnectionHandlerImpl connection) {
		this.dashboardConnections.remove(connection.getUserEmail());
	}

}
