package org.flexiblepower.defpi.dashboardgateway;

import javax.annotation.Generated;

/**
 * DashboardGatewayConfiguration provides the interface for the Dashboard Gateway service
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
 * Template by TNO, 2017
 * 
 * @author wilco
 */
@Generated(value = "org.flexiblepower.plugin.servicegen", date = "Oct 17, 2017 3:53:41 PM")
public interface DashboardGatewayConfiguration {



}