package org.flexiblepower.defpi.dashboard.gateway;

import javax.annotation.Generated;

import org.flexiblepower.defpi.dashboard.Dashboard;
import org.flexiblepower.defpi.dashboard.gateway.http.Gateway_httpConnectionHandlerImpl;
import org.flexiblepower.defpi.dashboard.gateway.http.Gateway_httpConnectionHandler;
import org.flexiblepower.service.Connection;

/**
 * GatewayConnectionManagerImpl
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file is generated as a stub, and has to be implemented by the user. Re-running the codegen plugin will
 * 		 not change the contents of this file.
 * Template by TNO, 2017
 * 
 * @author wilco
 */
@Generated(value = "org.flexiblepower.plugin.servicegen", date = "Oct 26, 2017 12:58:33 PM")
public class GatewayConnectionManagerImpl implements GatewayConnectionManager {

	private final Dashboard service;
	
	/**
	 * Auto-generated constructor building the factory for ConnectionHandlers of the provided service
	 *
	 * @param service The service that will be used as argument to instantiate the ConnectionHandlers
	 */
	public GatewayConnectionManagerImpl(Dashboard service) {
		this.service = service;
	}

	@Override
	public Gateway_httpConnectionHandler buildHttp(Connection connection) {
		return new Gateway_httpConnectionHandlerImpl(connection, this.service);
	}

}

