package org.flexiblepower.defpi.dashboard.gateway;

import javax.annotation.Generated;

import org.flexiblepower.defpi.dashboard.gateway.http.Gateway_httpConnectionHandler;
import org.flexiblepower.service.Connection;
import org.flexiblepower.service.ConnectionHandlerManager;

/**
 * GatewayConnectionManagerImpl
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
 * Template by TNO, 2017
 * 
 * @author wilco
 */
@Generated(value = "org.flexiblepower.plugin.servicegen", date = "Oct 26, 2017 12:58:33 PM")
public interface GatewayConnectionManager extends ConnectionHandlerManager {

	public Gateway_httpConnectionHandler buildHttp(Connection connection);

}

