# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: dropback_interface_v002.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='dropback_interface_v002.proto',
  package='dropback_interface_v002',
  syntax='proto2',
  serialized_pb=_b('\n\x1d\x64ropback_interface_v002.proto\x12\x17\x64ropback_interface_v002\"#\n\x03Msg\x12\x0b\n\x03str\x18\x01 \x02(\t\x12\x0f\n\x07\x63ounter\x18\x02 \x02(\x03\"4\n\x05Reply\x12\x0b\n\x03str\x18\x01 \x02(\t\x12\x10\n\x08\x61nswerTo\x18\x02 \x02(\x03\x12\x0c\n\x04\x63ode\x18\x03 \x01(\x05')
)




_MSG = _descriptor.Descriptor(
  name='Msg',
  full_name='dropback_interface_v002.Msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str', full_name='dropback_interface_v002.Msg.str', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='counter', full_name='dropback_interface_v002.Msg.counter', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=58,
  serialized_end=93,
)


_REPLY = _descriptor.Descriptor(
  name='Reply',
  full_name='dropback_interface_v002.Reply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str', full_name='dropback_interface_v002.Reply.str', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='answerTo', full_name='dropback_interface_v002.Reply.answerTo', index=1,
      number=2, type=3, cpp_type=2, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='code', full_name='dropback_interface_v002.Reply.code', index=2,
      number=3, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=95,
  serialized_end=147,
)

DESCRIPTOR.message_types_by_name['Msg'] = _MSG
DESCRIPTOR.message_types_by_name['Reply'] = _REPLY
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Msg = _reflection.GeneratedProtocolMessageType('Msg', (_message.Message,), dict(
  DESCRIPTOR = _MSG,
  __module__ = 'dropback_interface_v002_pb2'
  # @@protoc_insertion_point(class_scope:dropback_interface_v002.Msg)
  ))
_sym_db.RegisterMessage(Msg)

Reply = _reflection.GeneratedProtocolMessageType('Reply', (_message.Message,), dict(
  DESCRIPTOR = _REPLY,
  __module__ = 'dropback_interface_v002_pb2'
  # @@protoc_insertion_point(class_scope:dropback_interface_v002.Reply)
  ))
_sym_db.RegisterMessage(Reply)


# @@protoc_insertion_point(module_scope)
