// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: src/main/resources/Service.proto

package org.flexiblepower.proto;

public final class ServiceProto {
  private ServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  /**
   * Protobuf enum {@code process.ProcessState}
   */
  public enum ProcessState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>STARTING = 0;</code>
     */
    STARTING(0, 0),
    /**
     * <code>INITIALIZING = 1;</code>
     */
    INITIALIZING(1, 1),
    /**
     * <code>RUNNING = 2;</code>
     */
    RUNNING(2, 2),
    /**
     * <code>SUSPENDED = 3;</code>
     */
    SUSPENDED(3, 3),
    /**
     * <code>TERMINATED = 4;</code>
     */
    TERMINATED(4, 4),
    ;

    /**
     * <code>STARTING = 0;</code>
     */
    public static final int STARTING_VALUE = 0;
    /**
     * <code>INITIALIZING = 1;</code>
     */
    public static final int INITIALIZING_VALUE = 1;
    /**
     * <code>RUNNING = 2;</code>
     */
    public static final int RUNNING_VALUE = 2;
    /**
     * <code>SUSPENDED = 3;</code>
     */
    public static final int SUSPENDED_VALUE = 3;
    /**
     * <code>TERMINATED = 4;</code>
     */
    public static final int TERMINATED_VALUE = 4;


    public final int getNumber() {
      return value;
    }

    public static ProcessState valueOf(int value) {
      switch (value) {
        case 0: return STARTING;
        case 1: return INITIALIZING;
        case 2: return RUNNING;
        case 3: return SUSPENDED;
        case 4: return TERMINATED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<ProcessState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        ProcessState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<ProcessState>() {
            public ProcessState findValueByNumber(int number) {
              return ProcessState.valueOf(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.flexiblepower.proto.ServiceProto.getDescriptor().getEnumTypes().get(0);
    }

    private static final ProcessState[] VALUES = values();

    public static ProcessState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }

    private final int index;
    private final int value;

    private ProcessState(int index, int value) {
      this.index = index;
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:process.ProcessState)
  }

  public interface GoToProcessStateMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:process.GoToProcessStateMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string processId = 1;</code>
     */
    boolean hasProcessId();
    /**
     * <code>required string processId = 1;</code>
     */
    java.lang.String getProcessId();
    /**
     * <code>required string processId = 1;</code>
     */
    com.google.protobuf.ByteString
        getProcessIdBytes();

    /**
     * <code>required .process.ProcessState targetState = 2;</code>
     */
    boolean hasTargetState();
    /**
     * <code>required .process.ProcessState targetState = 2;</code>
     */
    org.flexiblepower.proto.ServiceProto.ProcessState getTargetState();
  }
  /**
   * Protobuf type {@code process.GoToProcessStateMessage}
   */
  public  static final class GoToProcessStateMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:process.GoToProcessStateMessage)
      GoToProcessStateMessageOrBuilder {
    // Use GoToProcessStateMessage.newBuilder() to construct.
    private GoToProcessStateMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private GoToProcessStateMessage() {
      processId_ = "";
      targetState_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private GoToProcessStateMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              processId_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.flexiblepower.proto.ServiceProto.ProcessState value = org.flexiblepower.proto.ServiceProto.ProcessState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                targetState_ = rawValue;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.flexiblepower.proto.ServiceProto.internal_static_process_GoToProcessStateMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.flexiblepower.proto.ServiceProto.internal_static_process_GoToProcessStateMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage.class, org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage.Builder.class);
    }

    private int bitField0_;
    public static final int PROCESSID_FIELD_NUMBER = 1;
    private volatile java.lang.Object processId_;
    /**
     * <code>required string processId = 1;</code>
     */
    public boolean hasProcessId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string processId = 1;</code>
     */
    public java.lang.String getProcessId() {
      java.lang.Object ref = processId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          processId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string processId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProcessIdBytes() {
      java.lang.Object ref = processId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int TARGETSTATE_FIELD_NUMBER = 2;
    private int targetState_;
    /**
     * <code>required .process.ProcessState targetState = 2;</code>
     */
    public boolean hasTargetState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .process.ProcessState targetState = 2;</code>
     */
    public org.flexiblepower.proto.ServiceProto.ProcessState getTargetState() {
      org.flexiblepower.proto.ServiceProto.ProcessState result = org.flexiblepower.proto.ServiceProto.ProcessState.valueOf(targetState_);
      return result == null ? org.flexiblepower.proto.ServiceProto.ProcessState.STARTING : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasProcessId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasTargetState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, processId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, targetState_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, processId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, targetState_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code process.GoToProcessStateMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:process.GoToProcessStateMessage)
        org.flexiblepower.proto.ServiceProto.GoToProcessStateMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.flexiblepower.proto.ServiceProto.internal_static_process_GoToProcessStateMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.flexiblepower.proto.ServiceProto.internal_static_process_GoToProcessStateMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage.class, org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage.Builder.class);
      }

      // Construct using org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        processId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        targetState_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.flexiblepower.proto.ServiceProto.internal_static_process_GoToProcessStateMessage_descriptor;
      }

      public org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage getDefaultInstanceForType() {
        return org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage.getDefaultInstance();
      }

      public org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage build() {
        org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage buildPartial() {
        org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage result = new org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.processId_ = processId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.targetState_ = targetState_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage) {
          return mergeFrom((org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage other) {
        if (other == org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage.getDefaultInstance()) return this;
        if (other.hasProcessId()) {
          bitField0_ |= 0x00000001;
          processId_ = other.processId_;
          onChanged();
        }
        if (other.hasTargetState()) {
          setTargetState(other.getTargetState());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasProcessId()) {
          return false;
        }
        if (!hasTargetState()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object processId_ = "";
      /**
       * <code>required string processId = 1;</code>
       */
      public boolean hasProcessId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public java.lang.String getProcessId() {
        java.lang.Object ref = processId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            processId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProcessIdBytes() {
        java.lang.Object ref = processId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          processId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public Builder setProcessId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        processId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public Builder clearProcessId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        processId_ = getDefaultInstance().getProcessId();
        onChanged();
        return this;
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public Builder setProcessIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        processId_ = value;
        onChanged();
        return this;
      }

      private int targetState_ = 0;
      /**
       * <code>required .process.ProcessState targetState = 2;</code>
       */
      public boolean hasTargetState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .process.ProcessState targetState = 2;</code>
       */
      public org.flexiblepower.proto.ServiceProto.ProcessState getTargetState() {
        org.flexiblepower.proto.ServiceProto.ProcessState result = org.flexiblepower.proto.ServiceProto.ProcessState.valueOf(targetState_);
        return result == null ? org.flexiblepower.proto.ServiceProto.ProcessState.STARTING : result;
      }
      /**
       * <code>required .process.ProcessState targetState = 2;</code>
       */
      public Builder setTargetState(org.flexiblepower.proto.ServiceProto.ProcessState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        targetState_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .process.ProcessState targetState = 2;</code>
       */
      public Builder clearTargetState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        targetState_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:process.GoToProcessStateMessage)
    }

    // @@protoc_insertion_point(class_scope:process.GoToProcessStateMessage)
    private static final org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage();
    }

    public static org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<GoToProcessStateMessage>
        PARSER = new com.google.protobuf.AbstractParser<GoToProcessStateMessage>() {
      public GoToProcessStateMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new GoToProcessStateMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<GoToProcessStateMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<GoToProcessStateMessage> getParserForType() {
      return PARSER;
    }

    public org.flexiblepower.proto.ServiceProto.GoToProcessStateMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ResumeProcessMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:process.ResumeProcessMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string processId = 1;</code>
     */
    boolean hasProcessId();
    /**
     * <code>required string processId = 1;</code>
     */
    java.lang.String getProcessId();
    /**
     * <code>required string processId = 1;</code>
     */
    com.google.protobuf.ByteString
        getProcessIdBytes();

    /**
     * <code>required bytes stateData = 2;</code>
     */
    boolean hasStateData();
    /**
     * <code>required bytes stateData = 2;</code>
     */
    com.google.protobuf.ByteString getStateData();
  }
  /**
   * Protobuf type {@code process.ResumeProcessMessage}
   */
  public  static final class ResumeProcessMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:process.ResumeProcessMessage)
      ResumeProcessMessageOrBuilder {
    // Use ResumeProcessMessage.newBuilder() to construct.
    private ResumeProcessMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ResumeProcessMessage() {
      processId_ = "";
      stateData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ResumeProcessMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              processId_ = bs;
              break;
            }
            case 18: {
              bitField0_ |= 0x00000002;
              stateData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.flexiblepower.proto.ServiceProto.internal_static_process_ResumeProcessMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.flexiblepower.proto.ServiceProto.internal_static_process_ResumeProcessMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.flexiblepower.proto.ServiceProto.ResumeProcessMessage.class, org.flexiblepower.proto.ServiceProto.ResumeProcessMessage.Builder.class);
    }

    private int bitField0_;
    public static final int PROCESSID_FIELD_NUMBER = 1;
    private volatile java.lang.Object processId_;
    /**
     * <code>required string processId = 1;</code>
     */
    public boolean hasProcessId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string processId = 1;</code>
     */
    public java.lang.String getProcessId() {
      java.lang.Object ref = processId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          processId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string processId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProcessIdBytes() {
      java.lang.Object ref = processId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATEDATA_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString stateData_;
    /**
     * <code>required bytes stateData = 2;</code>
     */
    public boolean hasStateData() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bytes stateData = 2;</code>
     */
    public com.google.protobuf.ByteString getStateData() {
      return stateData_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasProcessId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasStateData()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, processId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(2, stateData_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, processId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, stateData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.flexiblepower.proto.ServiceProto.ResumeProcessMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.flexiblepower.proto.ServiceProto.ResumeProcessMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.flexiblepower.proto.ServiceProto.ResumeProcessMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.flexiblepower.proto.ServiceProto.ResumeProcessMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.flexiblepower.proto.ServiceProto.ResumeProcessMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.flexiblepower.proto.ServiceProto.ResumeProcessMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.flexiblepower.proto.ServiceProto.ResumeProcessMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.flexiblepower.proto.ServiceProto.ResumeProcessMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.flexiblepower.proto.ServiceProto.ResumeProcessMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.flexiblepower.proto.ServiceProto.ResumeProcessMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.flexiblepower.proto.ServiceProto.ResumeProcessMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code process.ResumeProcessMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:process.ResumeProcessMessage)
        org.flexiblepower.proto.ServiceProto.ResumeProcessMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.flexiblepower.proto.ServiceProto.internal_static_process_ResumeProcessMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.flexiblepower.proto.ServiceProto.internal_static_process_ResumeProcessMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.flexiblepower.proto.ServiceProto.ResumeProcessMessage.class, org.flexiblepower.proto.ServiceProto.ResumeProcessMessage.Builder.class);
      }

      // Construct using org.flexiblepower.proto.ServiceProto.ResumeProcessMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        processId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        stateData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.flexiblepower.proto.ServiceProto.internal_static_process_ResumeProcessMessage_descriptor;
      }

      public org.flexiblepower.proto.ServiceProto.ResumeProcessMessage getDefaultInstanceForType() {
        return org.flexiblepower.proto.ServiceProto.ResumeProcessMessage.getDefaultInstance();
      }

      public org.flexiblepower.proto.ServiceProto.ResumeProcessMessage build() {
        org.flexiblepower.proto.ServiceProto.ResumeProcessMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.flexiblepower.proto.ServiceProto.ResumeProcessMessage buildPartial() {
        org.flexiblepower.proto.ServiceProto.ResumeProcessMessage result = new org.flexiblepower.proto.ServiceProto.ResumeProcessMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.processId_ = processId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.stateData_ = stateData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.flexiblepower.proto.ServiceProto.ResumeProcessMessage) {
          return mergeFrom((org.flexiblepower.proto.ServiceProto.ResumeProcessMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.flexiblepower.proto.ServiceProto.ResumeProcessMessage other) {
        if (other == org.flexiblepower.proto.ServiceProto.ResumeProcessMessage.getDefaultInstance()) return this;
        if (other.hasProcessId()) {
          bitField0_ |= 0x00000001;
          processId_ = other.processId_;
          onChanged();
        }
        if (other.hasStateData()) {
          setStateData(other.getStateData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasProcessId()) {
          return false;
        }
        if (!hasStateData()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.flexiblepower.proto.ServiceProto.ResumeProcessMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.flexiblepower.proto.ServiceProto.ResumeProcessMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object processId_ = "";
      /**
       * <code>required string processId = 1;</code>
       */
      public boolean hasProcessId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public java.lang.String getProcessId() {
        java.lang.Object ref = processId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            processId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProcessIdBytes() {
        java.lang.Object ref = processId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          processId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public Builder setProcessId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        processId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public Builder clearProcessId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        processId_ = getDefaultInstance().getProcessId();
        onChanged();
        return this;
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public Builder setProcessIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        processId_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString stateData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>required bytes stateData = 2;</code>
       */
      public boolean hasStateData() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bytes stateData = 2;</code>
       */
      public com.google.protobuf.ByteString getStateData() {
        return stateData_;
      }
      /**
       * <code>required bytes stateData = 2;</code>
       */
      public Builder setStateData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        stateData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bytes stateData = 2;</code>
       */
      public Builder clearStateData() {
        bitField0_ = (bitField0_ & ~0x00000002);
        stateData_ = getDefaultInstance().getStateData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:process.ResumeProcessMessage)
    }

    // @@protoc_insertion_point(class_scope:process.ResumeProcessMessage)
    private static final org.flexiblepower.proto.ServiceProto.ResumeProcessMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.flexiblepower.proto.ServiceProto.ResumeProcessMessage();
    }

    public static org.flexiblepower.proto.ServiceProto.ResumeProcessMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ResumeProcessMessage>
        PARSER = new com.google.protobuf.AbstractParser<ResumeProcessMessage>() {
      public ResumeProcessMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ResumeProcessMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<ResumeProcessMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ResumeProcessMessage> getParserForType() {
      return PARSER;
    }

    public org.flexiblepower.proto.ServiceProto.ResumeProcessMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface ProcessStateUpdateMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:process.ProcessStateUpdateMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string processId = 1;</code>
     */
    boolean hasProcessId();
    /**
     * <code>required string processId = 1;</code>
     */
    java.lang.String getProcessId();
    /**
     * <code>required string processId = 1;</code>
     */
    com.google.protobuf.ByteString
        getProcessIdBytes();

    /**
     * <code>required .process.ProcessState state = 2;</code>
     */
    boolean hasState();
    /**
     * <code>required .process.ProcessState state = 2;</code>
     */
    org.flexiblepower.proto.ServiceProto.ProcessState getState();

    /**
     * <code>optional bytes stateData = 3;</code>
     */
    boolean hasStateData();
    /**
     * <code>optional bytes stateData = 3;</code>
     */
    com.google.protobuf.ByteString getStateData();
  }
  /**
   * Protobuf type {@code process.ProcessStateUpdateMessage}
   */
  public  static final class ProcessStateUpdateMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:process.ProcessStateUpdateMessage)
      ProcessStateUpdateMessageOrBuilder {
    // Use ProcessStateUpdateMessage.newBuilder() to construct.
    private ProcessStateUpdateMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private ProcessStateUpdateMessage() {
      processId_ = "";
      state_ = 0;
      stateData_ = com.google.protobuf.ByteString.EMPTY;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ProcessStateUpdateMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              processId_ = bs;
              break;
            }
            case 16: {
              int rawValue = input.readEnum();
              org.flexiblepower.proto.ServiceProto.ProcessState value = org.flexiblepower.proto.ServiceProto.ProcessState.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(2, rawValue);
              } else {
                bitField0_ |= 0x00000002;
                state_ = rawValue;
              }
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              stateData_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.flexiblepower.proto.ServiceProto.internal_static_process_ProcessStateUpdateMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.flexiblepower.proto.ServiceProto.internal_static_process_ProcessStateUpdateMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage.class, org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage.Builder.class);
    }

    private int bitField0_;
    public static final int PROCESSID_FIELD_NUMBER = 1;
    private volatile java.lang.Object processId_;
    /**
     * <code>required string processId = 1;</code>
     */
    public boolean hasProcessId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string processId = 1;</code>
     */
    public java.lang.String getProcessId() {
      java.lang.Object ref = processId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          processId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string processId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProcessIdBytes() {
      java.lang.Object ref = processId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 2;
    private int state_;
    /**
     * <code>required .process.ProcessState state = 2;</code>
     */
    public boolean hasState() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required .process.ProcessState state = 2;</code>
     */
    public org.flexiblepower.proto.ServiceProto.ProcessState getState() {
      org.flexiblepower.proto.ServiceProto.ProcessState result = org.flexiblepower.proto.ServiceProto.ProcessState.valueOf(state_);
      return result == null ? org.flexiblepower.proto.ServiceProto.ProcessState.STARTING : result;
    }

    public static final int STATEDATA_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString stateData_;
    /**
     * <code>optional bytes stateData = 3;</code>
     */
    public boolean hasStateData() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bytes stateData = 3;</code>
     */
    public com.google.protobuf.ByteString getStateData() {
      return stateData_;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasProcessId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasState()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, processId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeEnum(2, state_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, stateData_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, processId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, state_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, stateData_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code process.ProcessStateUpdateMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:process.ProcessStateUpdateMessage)
        org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.flexiblepower.proto.ServiceProto.internal_static_process_ProcessStateUpdateMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.flexiblepower.proto.ServiceProto.internal_static_process_ProcessStateUpdateMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage.class, org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage.Builder.class);
      }

      // Construct using org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        processId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        state_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        stateData_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000004);
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.flexiblepower.proto.ServiceProto.internal_static_process_ProcessStateUpdateMessage_descriptor;
      }

      public org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage getDefaultInstanceForType() {
        return org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage.getDefaultInstance();
      }

      public org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage build() {
        org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage buildPartial() {
        org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage result = new org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.processId_ = processId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.state_ = state_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.stateData_ = stateData_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage) {
          return mergeFrom((org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage other) {
        if (other == org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage.getDefaultInstance()) return this;
        if (other.hasProcessId()) {
          bitField0_ |= 0x00000001;
          processId_ = other.processId_;
          onChanged();
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasStateData()) {
          setStateData(other.getStateData());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasProcessId()) {
          return false;
        }
        if (!hasState()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object processId_ = "";
      /**
       * <code>required string processId = 1;</code>
       */
      public boolean hasProcessId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public java.lang.String getProcessId() {
        java.lang.Object ref = processId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            processId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProcessIdBytes() {
        java.lang.Object ref = processId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          processId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public Builder setProcessId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        processId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public Builder clearProcessId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        processId_ = getDefaultInstance().getProcessId();
        onChanged();
        return this;
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public Builder setProcessIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        processId_ = value;
        onChanged();
        return this;
      }

      private int state_ = 0;
      /**
       * <code>required .process.ProcessState state = 2;</code>
       */
      public boolean hasState() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required .process.ProcessState state = 2;</code>
       */
      public org.flexiblepower.proto.ServiceProto.ProcessState getState() {
        org.flexiblepower.proto.ServiceProto.ProcessState result = org.flexiblepower.proto.ServiceProto.ProcessState.valueOf(state_);
        return result == null ? org.flexiblepower.proto.ServiceProto.ProcessState.STARTING : result;
      }
      /**
       * <code>required .process.ProcessState state = 2;</code>
       */
      public Builder setState(org.flexiblepower.proto.ServiceProto.ProcessState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000002;
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>required .process.ProcessState state = 2;</code>
       */
      public Builder clearState() {
        bitField0_ = (bitField0_ & ~0x00000002);
        state_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString stateData_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes stateData = 3;</code>
       */
      public boolean hasStateData() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bytes stateData = 3;</code>
       */
      public com.google.protobuf.ByteString getStateData() {
        return stateData_;
      }
      /**
       * <code>optional bytes stateData = 3;</code>
       */
      public Builder setStateData(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        stateData_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes stateData = 3;</code>
       */
      public Builder clearStateData() {
        bitField0_ = (bitField0_ & ~0x00000004);
        stateData_ = getDefaultInstance().getStateData();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:process.ProcessStateUpdateMessage)
    }

    // @@protoc_insertion_point(class_scope:process.ProcessStateUpdateMessage)
    private static final org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage();
    }

    public static org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<ProcessStateUpdateMessage>
        PARSER = new com.google.protobuf.AbstractParser<ProcessStateUpdateMessage>() {
      public ProcessStateUpdateMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new ProcessStateUpdateMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<ProcessStateUpdateMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ProcessStateUpdateMessage> getParserForType() {
      return PARSER;
    }

    public org.flexiblepower.proto.ServiceProto.ProcessStateUpdateMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface SetConfigMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:process.SetConfigMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required string processId = 1;</code>
     */
    boolean hasProcessId();
    /**
     * <code>required string processId = 1;</code>
     */
    java.lang.String getProcessId();
    /**
     * <code>required string processId = 1;</code>
     */
    com.google.protobuf.ByteString
        getProcessIdBytes();

    /**
     * <code>required bool isUpdate = 2;</code>
     */
    boolean hasIsUpdate();
    /**
     * <code>required bool isUpdate = 2;</code>
     */
    boolean getIsUpdate();

    /**
     * <code>map&lt;string, string&gt; config = 3;</code>
     */
    java.util.Map<java.lang.String, java.lang.String>
    getConfig();
  }
  /**
   * Protobuf type {@code process.SetConfigMessage}
   */
  public  static final class SetConfigMessage extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:process.SetConfigMessage)
      SetConfigMessageOrBuilder {
    // Use SetConfigMessage.newBuilder() to construct.
    private SetConfigMessage(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private SetConfigMessage() {
      processId_ = "";
      isUpdate_ = false;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private SetConfigMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
      this();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000001;
              processId_ = bs;
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              isUpdate_ = input.readBool();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                config_ = com.google.protobuf.MapField.newMapField(
                    ConfigDefaultEntryHolder.defaultEntry);
                mutable_bitField0_ |= 0x00000004;
              }
              com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
              config = input.readMessage(
                  ConfigDefaultEntryHolder.defaultEntry.getParserForType(), extensionRegistry);
              config_.getMutableMap().put(config.getKey(), config.getValue());
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw new RuntimeException(e.setUnfinishedMessage(this));
      } catch (java.io.IOException e) {
        throw new RuntimeException(
            new com.google.protobuf.InvalidProtocolBufferException(
                e.getMessage()).setUnfinishedMessage(this));
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.flexiblepower.proto.ServiceProto.internal_static_process_SetConfigMessage_descriptor;
    }

    @SuppressWarnings({"rawtypes"})
    protected com.google.protobuf.MapField internalGetMapField(
        int number) {
      switch (number) {
        case 3:
          return internalGetConfig();
        default:
          throw new RuntimeException(
              "Invalid map field number: " + number);
      }
    }
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.flexiblepower.proto.ServiceProto.internal_static_process_SetConfigMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              org.flexiblepower.proto.ServiceProto.SetConfigMessage.class, org.flexiblepower.proto.ServiceProto.SetConfigMessage.Builder.class);
    }

    private int bitField0_;
    public static final int PROCESSID_FIELD_NUMBER = 1;
    private volatile java.lang.Object processId_;
    /**
     * <code>required string processId = 1;</code>
     */
    public boolean hasProcessId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string processId = 1;</code>
     */
    public java.lang.String getProcessId() {
      java.lang.Object ref = processId_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          processId_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string processId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getProcessIdBytes() {
      java.lang.Object ref = processId_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        processId_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ISUPDATE_FIELD_NUMBER = 2;
    private boolean isUpdate_;
    /**
     * <code>required bool isUpdate = 2;</code>
     */
    public boolean hasIsUpdate() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required bool isUpdate = 2;</code>
     */
    public boolean getIsUpdate() {
      return isUpdate_;
    }

    public static final int CONFIG_FIELD_NUMBER = 3;
    private static final class ConfigDefaultEntryHolder {
      static final com.google.protobuf.MapEntry<
          java.lang.String, java.lang.String> defaultEntry =
              com.google.protobuf.MapEntry
              .<java.lang.String, java.lang.String>newDefaultInstance(
                  org.flexiblepower.proto.ServiceProto.internal_static_process_SetConfigMessage_ConfigEntry_descriptor, 
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "",
                  com.google.protobuf.WireFormat.FieldType.STRING,
                  "");
    }
    private com.google.protobuf.MapField<
        java.lang.String, java.lang.String> config_;
    private com.google.protobuf.MapField<java.lang.String, java.lang.String>
    internalGetConfig() {
      if (config_ == null) {
        return com.google.protobuf.MapField.emptyMapField(
            ConfigDefaultEntryHolder.defaultEntry);
     }
      return config_;
    }
    /**
     * <code>map&lt;string, string&gt; config = 3;</code>
     */

    public java.util.Map<java.lang.String, java.lang.String> getConfig() {
      return internalGetConfig().getMap();
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasProcessId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasIsUpdate()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        com.google.protobuf.GeneratedMessage.writeString(output, 1, processId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBool(2, isUpdate_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetConfig().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        config = ConfigDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        output.writeMessage(3, config);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.GeneratedMessage.computeStringSize(1, processId_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(2, isUpdate_);
      }
      for (java.util.Map.Entry<java.lang.String, java.lang.String> entry
           : internalGetConfig().getMap().entrySet()) {
        com.google.protobuf.MapEntry<java.lang.String, java.lang.String>
        config = ConfigDefaultEntryHolder.defaultEntry.newBuilderForType()
            .setKey(entry.getKey())
            .setValue(entry.getValue())
            .build();
        size += com.google.protobuf.CodedOutputStream
            .computeMessageSize(3, config);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    public static org.flexiblepower.proto.ServiceProto.SetConfigMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.flexiblepower.proto.ServiceProto.SetConfigMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.flexiblepower.proto.ServiceProto.SetConfigMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static org.flexiblepower.proto.ServiceProto.SetConfigMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static org.flexiblepower.proto.ServiceProto.SetConfigMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.flexiblepower.proto.ServiceProto.SetConfigMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static org.flexiblepower.proto.ServiceProto.SetConfigMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static org.flexiblepower.proto.ServiceProto.SetConfigMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static org.flexiblepower.proto.ServiceProto.SetConfigMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static org.flexiblepower.proto.ServiceProto.SetConfigMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(org.flexiblepower.proto.ServiceProto.SetConfigMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code process.SetConfigMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:process.SetConfigMessage)
        org.flexiblepower.proto.ServiceProto.SetConfigMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.flexiblepower.proto.ServiceProto.internal_static_process_SetConfigMessage_descriptor;
      }

      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetConfig();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      @SuppressWarnings({"rawtypes"})
      protected com.google.protobuf.MapField internalGetMutableMapField(
          int number) {
        switch (number) {
          case 3:
            return internalGetMutableConfig();
          default:
            throw new RuntimeException(
                "Invalid map field number: " + number);
        }
      }
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.flexiblepower.proto.ServiceProto.internal_static_process_SetConfigMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                org.flexiblepower.proto.ServiceProto.SetConfigMessage.class, org.flexiblepower.proto.ServiceProto.SetConfigMessage.Builder.class);
      }

      // Construct using org.flexiblepower.proto.ServiceProto.SetConfigMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        processId_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        isUpdate_ = false;
        bitField0_ = (bitField0_ & ~0x00000002);
        internalGetMutableConfig().clear();
        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.flexiblepower.proto.ServiceProto.internal_static_process_SetConfigMessage_descriptor;
      }

      public org.flexiblepower.proto.ServiceProto.SetConfigMessage getDefaultInstanceForType() {
        return org.flexiblepower.proto.ServiceProto.SetConfigMessage.getDefaultInstance();
      }

      public org.flexiblepower.proto.ServiceProto.SetConfigMessage build() {
        org.flexiblepower.proto.ServiceProto.SetConfigMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public org.flexiblepower.proto.ServiceProto.SetConfigMessage buildPartial() {
        org.flexiblepower.proto.ServiceProto.SetConfigMessage result = new org.flexiblepower.proto.ServiceProto.SetConfigMessage(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.processId_ = processId_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.isUpdate_ = isUpdate_;
        result.config_ = internalGetConfig();
        result.config_.makeImmutable();
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.flexiblepower.proto.ServiceProto.SetConfigMessage) {
          return mergeFrom((org.flexiblepower.proto.ServiceProto.SetConfigMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(org.flexiblepower.proto.ServiceProto.SetConfigMessage other) {
        if (other == org.flexiblepower.proto.ServiceProto.SetConfigMessage.getDefaultInstance()) return this;
        if (other.hasProcessId()) {
          bitField0_ |= 0x00000001;
          processId_ = other.processId_;
          onChanged();
        }
        if (other.hasIsUpdate()) {
          setIsUpdate(other.getIsUpdate());
        }
        internalGetMutableConfig().mergeFrom(
            other.internalGetConfig());
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        if (!hasProcessId()) {
          return false;
        }
        if (!hasIsUpdate()) {
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        org.flexiblepower.proto.ServiceProto.SetConfigMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (org.flexiblepower.proto.ServiceProto.SetConfigMessage) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object processId_ = "";
      /**
       * <code>required string processId = 1;</code>
       */
      public boolean hasProcessId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public java.lang.String getProcessId() {
        java.lang.Object ref = processId_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            processId_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public com.google.protobuf.ByteString
          getProcessIdBytes() {
        java.lang.Object ref = processId_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          processId_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public Builder setProcessId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        processId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public Builder clearProcessId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        processId_ = getDefaultInstance().getProcessId();
        onChanged();
        return this;
      }
      /**
       * <code>required string processId = 1;</code>
       */
      public Builder setProcessIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        processId_ = value;
        onChanged();
        return this;
      }

      private boolean isUpdate_ ;
      /**
       * <code>required bool isUpdate = 2;</code>
       */
      public boolean hasIsUpdate() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required bool isUpdate = 2;</code>
       */
      public boolean getIsUpdate() {
        return isUpdate_;
      }
      /**
       * <code>required bool isUpdate = 2;</code>
       */
      public Builder setIsUpdate(boolean value) {
        bitField0_ |= 0x00000002;
        isUpdate_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required bool isUpdate = 2;</code>
       */
      public Builder clearIsUpdate() {
        bitField0_ = (bitField0_ & ~0x00000002);
        isUpdate_ = false;
        onChanged();
        return this;
      }

      private com.google.protobuf.MapField<
          java.lang.String, java.lang.String> config_;
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetConfig() {
        if (config_ == null) {
          return com.google.protobuf.MapField.emptyMapField(
              ConfigDefaultEntryHolder.defaultEntry);
       }
        return config_;
      }
      private com.google.protobuf.MapField<java.lang.String, java.lang.String>
      internalGetMutableConfig() {
        onChanged();;
        if (config_ == null) {
          config_ = com.google.protobuf.MapField.newMapField(
              ConfigDefaultEntryHolder.defaultEntry);
        }
        if (!config_.isMutable()) {
          config_ = config_.copy();
        }
        return config_;
      }
      /**
       * <code>map&lt;string, string&gt; config = 3;</code>
       */
      public java.util.Map<java.lang.String, java.lang.String> getConfig() {
        return internalGetConfig().getMap();
      }
      /**
       * <code>map&lt;string, string&gt; config = 3;</code>
       */
      public java.util.Map<java.lang.String, java.lang.String>
      getMutableConfig() {
        return internalGetMutableConfig().getMutableMap();
      }
      /**
       * <code>map&lt;string, string&gt; config = 3;</code>
       */
      public Builder putAllConfig(
          java.util.Map<java.lang.String, java.lang.String> values) {
        getMutableConfig().putAll(values);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:process.SetConfigMessage)
    }

    // @@protoc_insertion_point(class_scope:process.SetConfigMessage)
    private static final org.flexiblepower.proto.ServiceProto.SetConfigMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new org.flexiblepower.proto.ServiceProto.SetConfigMessage();
    }

    public static org.flexiblepower.proto.ServiceProto.SetConfigMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    @java.lang.Deprecated public static final com.google.protobuf.Parser<SetConfigMessage>
        PARSER = new com.google.protobuf.AbstractParser<SetConfigMessage>() {
      public SetConfigMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        try {
          return new SetConfigMessage(input, extensionRegistry);
        } catch (RuntimeException e) {
          if (e.getCause() instanceof
              com.google.protobuf.InvalidProtocolBufferException) {
            throw (com.google.protobuf.InvalidProtocolBufferException)
                e.getCause();
          }
          throw e;
        }
      }
    };

    public static com.google.protobuf.Parser<SetConfigMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<SetConfigMessage> getParserForType() {
      return PARSER;
    }

    public org.flexiblepower.proto.ServiceProto.SetConfigMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_process_GoToProcessStateMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_process_GoToProcessStateMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_process_ResumeProcessMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_process_ResumeProcessMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_process_ProcessStateUpdateMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_process_ProcessStateUpdateMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_process_SetConfigMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_process_SetConfigMessage_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_process_SetConfigMessage_ConfigEntry_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_process_SetConfigMessage_ConfigEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n src/main/resources/Service.proto\022\007proc" +
      "ess\"X\n\027GoToProcessStateMessage\022\021\n\tproces" +
      "sId\030\001 \002(\t\022*\n\013targetState\030\002 \002(\0162\025.process" +
      ".ProcessState\"<\n\024ResumeProcessMessage\022\021\n" +
      "\tprocessId\030\001 \002(\t\022\021\n\tstateData\030\002 \002(\014\"g\n\031P" +
      "rocessStateUpdateMessage\022\021\n\tprocessId\030\001 " +
      "\002(\t\022$\n\005state\030\002 \002(\0162\025.process.ProcessStat" +
      "e\022\021\n\tstateData\030\003 \001(\014\"\235\001\n\020SetConfigMessag" +
      "e\022\021\n\tprocessId\030\001 \002(\t\022\020\n\010isUpdate\030\002 \002(\010\0225" +
      "\n\006config\030\003 \003(\0132%.process.SetConfigMessag",
      "e.ConfigEntry\032-\n\013ConfigEntry\022\013\n\003key\030\001 \001(" +
      "\t\022\r\n\005value\030\002 \001(\t:\0028\001*Z\n\014ProcessState\022\014\n\010" +
      "STARTING\020\000\022\020\n\014INITIALIZING\020\001\022\013\n\007RUNNING\020" +
      "\002\022\r\n\tSUSPENDED\020\003\022\016\n\nTERMINATED\020\004B\'\n\027org." +
      "flexiblepower.protoB\014ServiceProto"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_process_GoToProcessStateMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_process_GoToProcessStateMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_process_GoToProcessStateMessage_descriptor,
        new java.lang.String[] { "ProcessId", "TargetState", });
    internal_static_process_ResumeProcessMessage_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_process_ResumeProcessMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_process_ResumeProcessMessage_descriptor,
        new java.lang.String[] { "ProcessId", "StateData", });
    internal_static_process_ProcessStateUpdateMessage_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_process_ProcessStateUpdateMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_process_ProcessStateUpdateMessage_descriptor,
        new java.lang.String[] { "ProcessId", "State", "StateData", });
    internal_static_process_SetConfigMessage_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_process_SetConfigMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_process_SetConfigMessage_descriptor,
        new java.lang.String[] { "ProcessId", "IsUpdate", "Config", });
    internal_static_process_SetConfigMessage_ConfigEntry_descriptor =
      internal_static_process_SetConfigMessage_descriptor.getNestedTypes().get(0);
    internal_static_process_SetConfigMessage_ConfigEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_process_SetConfigMessage_ConfigEntry_descriptor,
        new java.lang.String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
