from "v001" import DropbackInterface_v001ConnectionHandler

class DropbackInterfaceConnectionManagerImpl(DropbackInterfaceConnectionManager):
    """ DropbackInterfaceConnectionManagerImpl
        Manages all connection handlers for the Echo Service service
        Generated by Python code generator for dEF-Pi at Oct 23, 2017 5:18:58 PM by coenvl
    
        NOTE: This file is generated as a stub, and has to be implemented by the user. Re-running the codegen plugin will 
        not change the contents of this file.
        
        Template by TNO, 2017 """
 
    def __init__(self, service):
        """ Auto-generated constructor building the manager for the provided service """
        self.__service = service       
    
    def build_sendonly(self, connection):
        """ Build version sendonly of the connection handler """
        return DropbackInterface_sendonlyConnectionHandlerImpl(self.__service, connection)

    
    def build_v001(self, connection):
        """ Build version v001 of the connection handler """
        return DropbackInterface_v001ConnectionHandlerImpl(self.__service, connection)

    
    def build_v002(self, connection):
        """ Build version v002 of the connection handler """
        return DropbackInterface_v002ConnectionHandlerImpl(self.__service, connection)
