from abc import ABCMeta, abstractmethod

class DropbackInterfaceConnectionManager:
    """ DropbackInterfaceConnectionManager
        Abstract base class for connection handler manager
        Generated by Python code generator for dEF-Pi at Oct 23, 2017 5:18:58 PM by coenvl
    
        NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
        
        Template by TNO, 2017 """
        
    __metaclass__ = ABCMeta
    
    @abstractmethod
    def build_v001(self, connection): pass

    
    @abstractmethod
    def build_sendonly(self, connection): pass

    
    @abstractmethod
    def build_v002(self, connection): pass
