# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DropbackInterfaceV001.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='DropbackInterfaceV001.proto',
  package='DropbackInterfaceV001',
  syntax='proto2',
  serialized_pb=_b('\n\x1b\x44ropbackInterfaceV001.proto\x12\x15\x44ropbackInterfaceV001\"#\n\x03Msg\x12\x0b\n\x03str\x18\x01 \x02(\t\x12\x0f\n\x07\x63ounter\x18\x02 \x02(\x05')
)




_MSG = _descriptor.Descriptor(
  name='Msg',
  full_name='DropbackInterfaceV001.Msg',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='str', full_name='DropbackInterfaceV001.Msg.str', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='counter', full_name='DropbackInterfaceV001.Msg.counter', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=54,
  serialized_end=89,
)

DESCRIPTOR.message_types_by_name['Msg'] = _MSG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Msg = _reflection.GeneratedProtocolMessageType('Msg', (_message.Message,), dict(
  DESCRIPTOR = _MSG,
  __module__ = 'DropbackInterfaceV001_pb2'
  # @@protoc_insertion_point(class_scope:DropbackInterfaceV001.Msg)
  ))
_sym_db.RegisterMessage(Msg)


# @@protoc_insertion_point(module_scope)
