from . import EchoInterfaceConnectionManager
from .v001 import EchoInterfaceV001ConnectionHandlerImpl


class EchoInterfaceConnectionManagerImpl(EchoInterfaceConnectionManager):
    """ EchoInterfaceConnectionManagerImpl
        Manages all connection handlers for the Echo Service service
        Generated by Python code generator for dEF-Pi at Oct 23, 2017 5:18:58 PM by coenvl
    
        NOTE: This file is generated as a stub, and has to be implemented by the user. Re-running the codegen plugin will 
        not change the contents of this file.
        
        Template by TNO, 2017 """
 
    def __init__(self, service):
        """ Auto-generated constructor building the manager for the provided service """
        self.__service = service       
    
    def build_v001(self, connection):
        """ Build version v001 of the connection handler """
        return EchoInterfaceV001ConnectionHandlerImpl(self.__service, connection)
