name: 'Echo Service'
descriptors:
  Message:
    file: 'message.proto'
    source: 'protobuf'
interfaces:
  - name: 'Echo Interface'
    classPrefix: 'Echo'
    autoConnect: false
    cardinality: 1
    subscribe: 
      - descriptor: Message
        type: Message
    publish: 
      - descriptor: Message
        type: Message