// Generated by the protocol buffer compiler. DO NOT EDIT!
// source: session.proto

package org.flexiblepower.service.proto;

public final class SessionProto {

    private SessionProto() {
    }

    public static void registerAllExtensions(final com.google.protobuf.ExtensionRegistry registry) {
    }

    public interface SessionOrBuilder extends
            // @@protoc_insertion_point(interface_extends:message.Session)
            com.google.protobuf.MessageOrBuilder {

        /**
         * <code>required .message.Session.ModeType mode = 1;</code>
         */
        boolean hasMode();

        /**
         * <code>required .message.Session.ModeType mode = 1;</code>
         */
        org.flexiblepower.service.proto.SessionProto.Session.ModeType getMode();

        /**
         * <code>required string id = 2;</code>
         */
        boolean hasId();

        /**
         * <code>required string id = 2;</code>
         */
        java.lang.String getId();

        /**
         * <code>required string id = 2;</code>
         */
        com.google.protobuf.ByteString getIdBytes();

        /**
         * <code>optional string address = 3;</code>
         */
        boolean hasAddress();

        /**
         * <code>optional string address = 3;</code>
         */
        java.lang.String getAddress();

        /**
         * <code>optional string address = 3;</code>
         */
        com.google.protobuf.ByteString getAddressBytes();

        /**
         * <code>optional int32 port = 4;</code>
         */
        boolean hasPort();

        /**
         * <code>optional int32 port = 4;</code>
         */
        int getPort();

        /**
         * <code>optional string subscribeHash = 5;</code>
         */
        boolean hasSubscribeHash();

        /**
         * <code>optional string subscribeHash = 5;</code>
         */
        java.lang.String getSubscribeHash();

        /**
         * <code>optional string subscribeHash = 5;</code>
         */
        com.google.protobuf.ByteString getSubscribeHashBytes();

        /**
         * <code>optional string publishHash = 6;</code>
         */
        boolean hasPublishHash();

        /**
         * <code>optional string publishHash = 6;</code>
         */
        java.lang.String getPublishHash();

        /**
         * <code>optional string publishHash = 6;</code>
         */
        com.google.protobuf.ByteString getPublishHashBytes();
    }

    /**
     * Protobuf type {@code message.Session}
     */
    public static final class Session extends com.google.protobuf.GeneratedMessage implements
            // @@protoc_insertion_point(message_implements:message.Session)
            SessionOrBuilder {

        // Use Session.newBuilder() to construct.
        private Session(final com.google.protobuf.GeneratedMessage.Builder<?> builder) {
            super(builder);
        }

        private Session() {
            this.mode_ = 0;
            this.id_ = "";
            this.address_ = "";
            this.port_ = 0;
            this.subscribeHash_ = "";
            this.publishHash_ = "";
        }

        @java.lang.Override
        public final com.google.protobuf.UnknownFieldSet getUnknownFields() {
            return this.unknownFields;
        }

        private Session(final com.google.protobuf.CodedInputStream input,
                final com.google.protobuf.ExtensionRegistryLite extensionRegistry) {
            this();
            final int mutable_bitField0_ = 0;
            final com.google.protobuf.UnknownFieldSet.Builder unknownFields = com.google.protobuf.UnknownFieldSet
                    .newBuilder();
            try {
                boolean done = false;
                while (!done) {
                    final int tag = input.readTag();
                    switch (tag) {
                    case 0:
                        done = true;
                        break;
                    default: {
                        if (!this.parseUnknownField(input, unknownFields, extensionRegistry, tag)) {
                            done = true;
                        }
                        break;
                    }
                    case 8: {
                        final int rawValue = input.readEnum();
                        final org.flexiblepower.service.proto.SessionProto.Session.ModeType value = org.flexiblepower.service.proto.SessionProto.Session.ModeType
                                .valueOf(rawValue);
                        if (value == null) {
                            unknownFields.mergeVarintField(1, rawValue);
                        } else {
                            this.bitField0_ |= 0x00000001;
                            this.mode_ = rawValue;
                        }
                        break;
                    }
                    case 18: {
                        final com.google.protobuf.ByteString bs = input.readBytes();
                        this.bitField0_ |= 0x00000002;
                        this.id_ = bs;
                        break;
                    }
                    case 26: {
                        final com.google.protobuf.ByteString bs = input.readBytes();
                        this.bitField0_ |= 0x00000004;
                        this.address_ = bs;
                        break;
                    }
                    case 32: {
                        this.bitField0_ |= 0x00000008;
                        this.port_ = input.readInt32();
                        break;
                    }
                    case 42: {
                        final com.google.protobuf.ByteString bs = input.readBytes();
                        this.bitField0_ |= 0x00000010;
                        this.subscribeHash_ = bs;
                        break;
                    }
                    case 50: {
                        final com.google.protobuf.ByteString bs = input.readBytes();
                        this.bitField0_ |= 0x00000020;
                        this.publishHash_ = bs;
                        break;
                    }
                    }
                }
            } catch (final com.google.protobuf.InvalidProtocolBufferException e) {
                throw new RuntimeException(e.setUnfinishedMessage(this));
            } catch (final java.io.IOException e) {
                throw new RuntimeException(new com.google.protobuf.InvalidProtocolBufferException(e.getMessage())
                        .setUnfinishedMessage(this));
            } finally {
                this.unknownFields = unknownFields.build();
                this.makeExtensionsImmutable();
            }
        }

        public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
            return org.flexiblepower.service.proto.SessionProto.internal_static_message_Session_descriptor;
        }

        @Override
        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
            return org.flexiblepower.service.proto.SessionProto.internal_static_message_Session_fieldAccessorTable
                    .ensureFieldAccessorsInitialized(org.flexiblepower.service.proto.SessionProto.Session.class,
                            org.flexiblepower.service.proto.SessionProto.Session.Builder.class);
        }

        /**
         * Protobuf enum {@code message.Session.ModeType}
         */
        public enum ModeType implements com.google.protobuf.ProtocolMessageEnum {
            /**
             * <code>CREATE = 0;</code>
             */
            CREATE(0, 0),
            /**
             * <code>DELETE = 1;</code>
             */
            DELETE(1, 1),;

            /**
             * <code>CREATE = 0;</code>
             */
            public static final int CREATE_VALUE = 0;
            /**
             * <code>DELETE = 1;</code>
             */
            public static final int DELETE_VALUE = 1;

            @Override
            public final int getNumber() {
                return this.value;
            }

            public static ModeType valueOf(final int value) {
                switch (value) {
                case 0:
                    return CREATE;
                case 1:
                    return DELETE;
                default:
                    return null;
                }
            }

            public static com.google.protobuf.Internal.EnumLiteMap<ModeType> internalGetValueMap() {
                return ModeType.internalValueMap;
            }

            private static final com.google.protobuf.Internal.EnumLiteMap<ModeType> internalValueMap = new com.google.protobuf.Internal.EnumLiteMap<ModeType>() {

                @Override
                public ModeType findValueByNumber(final int number) {
                    return ModeType.valueOf(number);
                }
            };

            @Override
            public final com.google.protobuf.Descriptors.EnumValueDescriptor getValueDescriptor() {
                return ModeType.getDescriptor().getValues().get(this.index);
            }

            @Override
            public final com.google.protobuf.Descriptors.EnumDescriptor getDescriptorForType() {
                return ModeType.getDescriptor();
            }

            public static final com.google.protobuf.Descriptors.EnumDescriptor getDescriptor() {
                return org.flexiblepower.service.proto.SessionProto.Session.getDescriptor().getEnumTypes().get(0);
            }

            private static final ModeType[] VALUES = ModeType.values();

            public static ModeType valueOf(final com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
                if (desc.getType() != ModeType.getDescriptor()) {
                    throw new java.lang.IllegalArgumentException("EnumValueDescriptor is not for this type.");
                }
                return ModeType.VALUES[desc.getIndex()];
            }

            private final int index;
            private final int value;

            private ModeType(final int index, final int value) {
                this.index = index;
                this.value = value;
            }

            // @@protoc_insertion_point(enum_scope:message.Session.ModeType)
        }

        private int bitField0_;
        public static final int MODE_FIELD_NUMBER = 1;
        private int mode_;

        /**
         * <code>required .message.Session.ModeType mode = 1;</code>
         */
        @Override
        public boolean hasMode() {
            return ((this.bitField0_ & 0x00000001) == 0x00000001);
        }

        /**
         * <code>required .message.Session.ModeType mode = 1;</code>
         */
        @Override
        public org.flexiblepower.service.proto.SessionProto.Session.ModeType getMode() {
            final org.flexiblepower.service.proto.SessionProto.Session.ModeType result = org.flexiblepower.service.proto.SessionProto.Session.ModeType
                    .valueOf(this.mode_);
            return result == null ? org.flexiblepower.service.proto.SessionProto.Session.ModeType.CREATE : result;
        }

        public static final int ID_FIELD_NUMBER = 2;
        private volatile java.lang.Object id_;

        /**
         * <code>required string id = 2;</code>
         */
        @Override
        public boolean hasId() {
            return ((this.bitField0_ & 0x00000002) == 0x00000002);
        }

        /**
         * <code>required string id = 2;</code>
         */
        @Override
        public java.lang.String getId() {
            final java.lang.Object ref = this.id_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                final java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    this.id_ = s;
                }
                return s;
            }
        }

        /**
         * <code>required string id = 2;</code>
         */
        @Override
        public com.google.protobuf.ByteString getIdBytes() {
            final java.lang.Object ref = this.id_;
            if (ref instanceof java.lang.String) {
                final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                        .copyFromUtf8((java.lang.String) ref);
                this.id_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int ADDRESS_FIELD_NUMBER = 3;
        private volatile java.lang.Object address_;

        /**
         * <code>optional string address = 3;</code>
         */
        @Override
        public boolean hasAddress() {
            return ((this.bitField0_ & 0x00000004) == 0x00000004);
        }

        /**
         * <code>optional string address = 3;</code>
         */
        @Override
        public java.lang.String getAddress() {
            final java.lang.Object ref = this.address_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                final java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    this.address_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string address = 3;</code>
         */
        @Override
        public com.google.protobuf.ByteString getAddressBytes() {
            final java.lang.Object ref = this.address_;
            if (ref instanceof java.lang.String) {
                final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                        .copyFromUtf8((java.lang.String) ref);
                this.address_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PORT_FIELD_NUMBER = 4;
        private int port_;

        /**
         * <code>optional int32 port = 4;</code>
         */
        @Override
        public boolean hasPort() {
            return ((this.bitField0_ & 0x00000008) == 0x00000008);
        }

        /**
         * <code>optional int32 port = 4;</code>
         */
        @Override
        public int getPort() {
            return this.port_;
        }

        public static final int SUBSCRIBEHASH_FIELD_NUMBER = 5;
        private volatile java.lang.Object subscribeHash_;

        /**
         * <code>optional string subscribeHash = 5;</code>
         */
        @Override
        public boolean hasSubscribeHash() {
            return ((this.bitField0_ & 0x00000010) == 0x00000010);
        }

        /**
         * <code>optional string subscribeHash = 5;</code>
         */
        @Override
        public java.lang.String getSubscribeHash() {
            final java.lang.Object ref = this.subscribeHash_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                final java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    this.subscribeHash_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string subscribeHash = 5;</code>
         */
        @Override
        public com.google.protobuf.ByteString getSubscribeHashBytes() {
            final java.lang.Object ref = this.subscribeHash_;
            if (ref instanceof java.lang.String) {
                final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                        .copyFromUtf8((java.lang.String) ref);
                this.subscribeHash_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        public static final int PUBLISHHASH_FIELD_NUMBER = 6;
        private volatile java.lang.Object publishHash_;

        /**
         * <code>optional string publishHash = 6;</code>
         */
        @Override
        public boolean hasPublishHash() {
            return ((this.bitField0_ & 0x00000020) == 0x00000020);
        }

        /**
         * <code>optional string publishHash = 6;</code>
         */
        @Override
        public java.lang.String getPublishHash() {
            final java.lang.Object ref = this.publishHash_;
            if (ref instanceof java.lang.String) {
                return (java.lang.String) ref;
            } else {
                final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                final java.lang.String s = bs.toStringUtf8();
                if (bs.isValidUtf8()) {
                    this.publishHash_ = s;
                }
                return s;
            }
        }

        /**
         * <code>optional string publishHash = 6;</code>
         */
        @Override
        public com.google.protobuf.ByteString getPublishHashBytes() {
            final java.lang.Object ref = this.publishHash_;
            if (ref instanceof java.lang.String) {
                final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                        .copyFromUtf8((java.lang.String) ref);
                this.publishHash_ = b;
                return b;
            } else {
                return (com.google.protobuf.ByteString) ref;
            }
        }

        private byte memoizedIsInitialized = -1;

        @Override
        public final boolean isInitialized() {
            final byte isInitialized = this.memoizedIsInitialized;
            if (isInitialized == 1) {
                return true;
            }
            if (isInitialized == 0) {
                return false;
            }

            if (!this.hasMode()) {
                this.memoizedIsInitialized = 0;
                return false;
            }
            if (!this.hasId()) {
                this.memoizedIsInitialized = 0;
                return false;
            }
            this.memoizedIsInitialized = 1;
            return true;
        }

        @Override
        public void writeTo(final com.google.protobuf.CodedOutputStream output) throws java.io.IOException {
            if (((this.bitField0_ & 0x00000001) == 0x00000001)) {
                output.writeEnum(1, this.mode_);
            }
            if (((this.bitField0_ & 0x00000002) == 0x00000002)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 2, this.id_);
            }
            if (((this.bitField0_ & 0x00000004) == 0x00000004)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 3, this.address_);
            }
            if (((this.bitField0_ & 0x00000008) == 0x00000008)) {
                output.writeInt32(4, this.port_);
            }
            if (((this.bitField0_ & 0x00000010) == 0x00000010)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 5, this.subscribeHash_);
            }
            if (((this.bitField0_ & 0x00000020) == 0x00000020)) {
                com.google.protobuf.GeneratedMessage.writeString(output, 6, this.publishHash_);
            }
            this.unknownFields.writeTo(output);
        }

        @Override
        public int getSerializedSize() {
            int size = this.memoizedSize;
            if (size != -1) {
                return size;
            }

            size = 0;
            if (((this.bitField0_ & 0x00000001) == 0x00000001)) {
                size += com.google.protobuf.CodedOutputStream.computeEnumSize(1, this.mode_);
            }
            if (((this.bitField0_ & 0x00000002) == 0x00000002)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(2, this.id_);
            }
            if (((this.bitField0_ & 0x00000004) == 0x00000004)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(3, this.address_);
            }
            if (((this.bitField0_ & 0x00000008) == 0x00000008)) {
                size += com.google.protobuf.CodedOutputStream.computeInt32Size(4, this.port_);
            }
            if (((this.bitField0_ & 0x00000010) == 0x00000010)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(5, this.subscribeHash_);
            }
            if (((this.bitField0_ & 0x00000020) == 0x00000020)) {
                size += com.google.protobuf.GeneratedMessage.computeStringSize(6, this.publishHash_);
            }
            size += this.unknownFields.getSerializedSize();
            this.memoizedSize = size;
            return size;
        }

        private static final long serialVersionUID = 0L;

        public static org.flexiblepower.service.proto.SessionProto.Session parseFrom(
                final com.google.protobuf.ByteString data) throws com.google.protobuf.InvalidProtocolBufferException {
            return Session.PARSER.parseFrom(data);
        }

        public static org.flexiblepower.service.proto.SessionProto.Session parseFrom(
                final com.google.protobuf.ByteString data,
                final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return Session.PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.flexiblepower.service.proto.SessionProto.Session parseFrom(final byte[] data)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return Session.PARSER.parseFrom(data);
        }

        public static org.flexiblepower.service.proto.SessionProto.Session parseFrom(final byte[] data,
                final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                throws com.google.protobuf.InvalidProtocolBufferException {
            return Session.PARSER.parseFrom(data, extensionRegistry);
        }

        public static org.flexiblepower.service.proto.SessionProto.Session parseFrom(final java.io.InputStream input)
                throws java.io.IOException {
            return Session.PARSER.parseFrom(input);
        }

        public static org.flexiblepower.service.proto.SessionProto.Session parseFrom(final java.io.InputStream input,
                final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return Session.PARSER.parseFrom(input, extensionRegistry);
        }

        public static org.flexiblepower.service.proto.SessionProto.Session
                parseDelimitedFrom(final java.io.InputStream input) throws java.io.IOException {
            return Session.PARSER.parseDelimitedFrom(input);
        }

        public static org.flexiblepower.service.proto.SessionProto.Session parseDelimitedFrom(
                final java.io.InputStream input,
                final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return Session.PARSER.parseDelimitedFrom(input, extensionRegistry);
        }

        public static org.flexiblepower.service.proto.SessionProto.Session
                parseFrom(final com.google.protobuf.CodedInputStream input) throws java.io.IOException {
            return Session.PARSER.parseFrom(input);
        }

        public static org.flexiblepower.service.proto.SessionProto.Session parseFrom(
                final com.google.protobuf.CodedInputStream input,
                final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
            return Session.PARSER.parseFrom(input, extensionRegistry);
        }

        @Override
        public Builder newBuilderForType() {
            return Session.newBuilder();
        }

        public static Builder newBuilder() {
            return Session.DEFAULT_INSTANCE.toBuilder();
        }

        public static Builder newBuilder(final org.flexiblepower.service.proto.SessionProto.Session prototype) {
            return Session.DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
        }

        @Override
        public Builder toBuilder() {
            return this == Session.DEFAULT_INSTANCE ? new Builder() : new Builder().mergeFrom(this);
        }

        @java.lang.Override
        protected Builder newBuilderForType(final com.google.protobuf.GeneratedMessage.BuilderParent parent) {
            final Builder builder = new Builder(parent);
            return builder;
        }

        /**
         * Protobuf type {@code message.Session}
         */
        public static final class Builder extends com.google.protobuf.GeneratedMessage.Builder<Builder> implements
                // @@protoc_insertion_point(builder_implements:message.Session)
                org.flexiblepower.service.proto.SessionProto.SessionOrBuilder {

            public static final com.google.protobuf.Descriptors.Descriptor getDescriptor() {
                return org.flexiblepower.service.proto.SessionProto.internal_static_message_Session_descriptor;
            }

            @Override
            protected com.google.protobuf.GeneratedMessage.FieldAccessorTable internalGetFieldAccessorTable() {
                return org.flexiblepower.service.proto.SessionProto.internal_static_message_Session_fieldAccessorTable
                        .ensureFieldAccessorsInitialized(org.flexiblepower.service.proto.SessionProto.Session.class,
                                org.flexiblepower.service.proto.SessionProto.Session.Builder.class);
            }

            // Construct using org.flexiblepower.service.proto.SessionProto.Session.newBuilder()
            private Builder() {
                this.maybeForceBuilderInitialization();
            }

            private Builder(final com.google.protobuf.GeneratedMessage.BuilderParent parent) {
                super(parent);
                this.maybeForceBuilderInitialization();
            }

            private void maybeForceBuilderInitialization() {
                if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
                }
            }

            @Override
            public Builder clear() {
                super.clear();
                this.mode_ = 0;
                this.bitField0_ = (this.bitField0_ & ~0x00000001);
                this.id_ = "";
                this.bitField0_ = (this.bitField0_ & ~0x00000002);
                this.address_ = "";
                this.bitField0_ = (this.bitField0_ & ~0x00000004);
                this.port_ = 0;
                this.bitField0_ = (this.bitField0_ & ~0x00000008);
                this.subscribeHash_ = "";
                this.bitField0_ = (this.bitField0_ & ~0x00000010);
                this.publishHash_ = "";
                this.bitField0_ = (this.bitField0_ & ~0x00000020);
                return this;
            }

            @Override
            public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
                return org.flexiblepower.service.proto.SessionProto.internal_static_message_Session_descriptor;
            }

            @Override
            public org.flexiblepower.service.proto.SessionProto.Session getDefaultInstanceForType() {
                return org.flexiblepower.service.proto.SessionProto.Session.getDefaultInstance();
            }

            @Override
            public org.flexiblepower.service.proto.SessionProto.Session build() {
                final org.flexiblepower.service.proto.SessionProto.Session result = this.buildPartial();
                if (!result.isInitialized()) {
                    throw Builder.newUninitializedMessageException(result);
                }
                return result;
            }

            @Override
            public org.flexiblepower.service.proto.SessionProto.Session buildPartial() {
                final org.flexiblepower.service.proto.SessionProto.Session result = new org.flexiblepower.service.proto.SessionProto.Session(
                        this);
                final int from_bitField0_ = this.bitField0_;
                int to_bitField0_ = 0;
                if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
                    to_bitField0_ |= 0x00000001;
                }
                result.mode_ = this.mode_;
                if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
                    to_bitField0_ |= 0x00000002;
                }
                result.id_ = this.id_;
                if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
                    to_bitField0_ |= 0x00000004;
                }
                result.address_ = this.address_;
                if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
                    to_bitField0_ |= 0x00000008;
                }
                result.port_ = this.port_;
                if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
                    to_bitField0_ |= 0x00000010;
                }
                result.subscribeHash_ = this.subscribeHash_;
                if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
                    to_bitField0_ |= 0x00000020;
                }
                result.publishHash_ = this.publishHash_;
                result.bitField0_ = to_bitField0_;
                this.onBuilt();
                return result;
            }

            @Override
            public Builder mergeFrom(final com.google.protobuf.Message other) {
                if (other instanceof org.flexiblepower.service.proto.SessionProto.Session) {
                    return this.mergeFrom((org.flexiblepower.service.proto.SessionProto.Session) other);
                } else {
                    super.mergeFrom(other);
                    return this;
                }
            }

            public Builder mergeFrom(final org.flexiblepower.service.proto.SessionProto.Session other) {
                if (other == org.flexiblepower.service.proto.SessionProto.Session.getDefaultInstance()) {
                    return this;
                }
                if (other.hasMode()) {
                    this.setMode(other.getMode());
                }
                if (other.hasId()) {
                    this.bitField0_ |= 0x00000002;
                    this.id_ = other.id_;
                    this.onChanged();
                }
                if (other.hasAddress()) {
                    this.bitField0_ |= 0x00000004;
                    this.address_ = other.address_;
                    this.onChanged();
                }
                if (other.hasPort()) {
                    this.setPort(other.getPort());
                }
                if (other.hasSubscribeHash()) {
                    this.bitField0_ |= 0x00000010;
                    this.subscribeHash_ = other.subscribeHash_;
                    this.onChanged();
                }
                if (other.hasPublishHash()) {
                    this.bitField0_ |= 0x00000020;
                    this.publishHash_ = other.publishHash_;
                    this.onChanged();
                }
                this.mergeUnknownFields(other.unknownFields);
                this.onChanged();
                return this;
            }

            @Override
            public final boolean isInitialized() {
                if (!this.hasMode()) {
                    return false;
                }
                if (!this.hasId()) {
                    return false;
                }
                return true;
            }

            @Override
            public Builder mergeFrom(final com.google.protobuf.CodedInputStream input,
                    final com.google.protobuf.ExtensionRegistryLite extensionRegistry) throws java.io.IOException {
                org.flexiblepower.service.proto.SessionProto.Session parsedMessage = null;
                try {
                    parsedMessage = Session.PARSER.parsePartialFrom(input, extensionRegistry);
                } catch (final com.google.protobuf.InvalidProtocolBufferException e) {
                    parsedMessage = (org.flexiblepower.service.proto.SessionProto.Session) e.getUnfinishedMessage();
                    throw e;
                } finally {
                    if (parsedMessage != null) {
                        this.mergeFrom(parsedMessage);
                    }
                }
                return this;
            }

            private int bitField0_;

            private int mode_ = 0;

            /**
             * <code>required .message.Session.ModeType mode = 1;</code>
             */
            @Override
            public boolean hasMode() {
                return ((this.bitField0_ & 0x00000001) == 0x00000001);
            }

            /**
             * <code>required .message.Session.ModeType mode = 1;</code>
             */
            @Override
            public org.flexiblepower.service.proto.SessionProto.Session.ModeType getMode() {
                final org.flexiblepower.service.proto.SessionProto.Session.ModeType result = org.flexiblepower.service.proto.SessionProto.Session.ModeType
                        .valueOf(this.mode_);
                return result == null ? org.flexiblepower.service.proto.SessionProto.Session.ModeType.CREATE : result;
            }

            /**
             * <code>required .message.Session.ModeType mode = 1;</code>
             */
            public Builder setMode(final org.flexiblepower.service.proto.SessionProto.Session.ModeType value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                this.bitField0_ |= 0x00000001;
                this.mode_ = value.getNumber();
                this.onChanged();
                return this;
            }

            /**
             * <code>required .message.Session.ModeType mode = 1;</code>
             */
            public Builder clearMode() {
                this.bitField0_ = (this.bitField0_ & ~0x00000001);
                this.mode_ = 0;
                this.onChanged();
                return this;
            }

            private java.lang.Object id_ = "";

            /**
             * <code>required string id = 2;</code>
             */
            @Override
            public boolean hasId() {
                return ((this.bitField0_ & 0x00000002) == 0x00000002);
            }

            /**
             * <code>required string id = 2;</code>
             */
            @Override
            public java.lang.String getId() {
                final java.lang.Object ref = this.id_;
                if (!(ref instanceof java.lang.String)) {
                    final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    final java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        this.id_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>required string id = 2;</code>
             */
            @Override
            public com.google.protobuf.ByteString getIdBytes() {
                final java.lang.Object ref = this.id_;
                if (ref instanceof String) {
                    final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    this.id_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>required string id = 2;</code>
             */
            public Builder setId(final java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                this.bitField0_ |= 0x00000002;
                this.id_ = value;
                this.onChanged();
                return this;
            }

            /**
             * <code>required string id = 2;</code>
             */
            public Builder clearId() {
                this.bitField0_ = (this.bitField0_ & ~0x00000002);
                this.id_ = Session.getDefaultInstance().getId();
                this.onChanged();
                return this;
            }

            /**
             * <code>required string id = 2;</code>
             */
            public Builder setIdBytes(final com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                this.bitField0_ |= 0x00000002;
                this.id_ = value;
                this.onChanged();
                return this;
            }

            private java.lang.Object address_ = "";

            /**
             * <code>optional string address = 3;</code>
             */
            @Override
            public boolean hasAddress() {
                return ((this.bitField0_ & 0x00000004) == 0x00000004);
            }

            /**
             * <code>optional string address = 3;</code>
             */
            @Override
            public java.lang.String getAddress() {
                final java.lang.Object ref = this.address_;
                if (!(ref instanceof java.lang.String)) {
                    final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    final java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        this.address_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string address = 3;</code>
             */
            @Override
            public com.google.protobuf.ByteString getAddressBytes() {
                final java.lang.Object ref = this.address_;
                if (ref instanceof String) {
                    final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    this.address_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string address = 3;</code>
             */
            public Builder setAddress(final java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                this.bitField0_ |= 0x00000004;
                this.address_ = value;
                this.onChanged();
                return this;
            }

            /**
             * <code>optional string address = 3;</code>
             */
            public Builder clearAddress() {
                this.bitField0_ = (this.bitField0_ & ~0x00000004);
                this.address_ = Session.getDefaultInstance().getAddress();
                this.onChanged();
                return this;
            }

            /**
             * <code>optional string address = 3;</code>
             */
            public Builder setAddressBytes(final com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                this.bitField0_ |= 0x00000004;
                this.address_ = value;
                this.onChanged();
                return this;
            }

            private int port_;

            /**
             * <code>optional int32 port = 4;</code>
             */
            @Override
            public boolean hasPort() {
                return ((this.bitField0_ & 0x00000008) == 0x00000008);
            }

            /**
             * <code>optional int32 port = 4;</code>
             */
            @Override
            public int getPort() {
                return this.port_;
            }

            /**
             * <code>optional int32 port = 4;</code>
             */
            public Builder setPort(final int value) {
                this.bitField0_ |= 0x00000008;
                this.port_ = value;
                this.onChanged();
                return this;
            }

            /**
             * <code>optional int32 port = 4;</code>
             */
            public Builder clearPort() {
                this.bitField0_ = (this.bitField0_ & ~0x00000008);
                this.port_ = 0;
                this.onChanged();
                return this;
            }

            private java.lang.Object subscribeHash_ = "";

            /**
             * <code>optional string subscribeHash = 5;</code>
             */
            @Override
            public boolean hasSubscribeHash() {
                return ((this.bitField0_ & 0x00000010) == 0x00000010);
            }

            /**
             * <code>optional string subscribeHash = 5;</code>
             */
            @Override
            public java.lang.String getSubscribeHash() {
                final java.lang.Object ref = this.subscribeHash_;
                if (!(ref instanceof java.lang.String)) {
                    final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    final java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        this.subscribeHash_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string subscribeHash = 5;</code>
             */
            @Override
            public com.google.protobuf.ByteString getSubscribeHashBytes() {
                final java.lang.Object ref = this.subscribeHash_;
                if (ref instanceof String) {
                    final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    this.subscribeHash_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string subscribeHash = 5;</code>
             */
            public Builder setSubscribeHash(final java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                this.bitField0_ |= 0x00000010;
                this.subscribeHash_ = value;
                this.onChanged();
                return this;
            }

            /**
             * <code>optional string subscribeHash = 5;</code>
             */
            public Builder clearSubscribeHash() {
                this.bitField0_ = (this.bitField0_ & ~0x00000010);
                this.subscribeHash_ = Session.getDefaultInstance().getSubscribeHash();
                this.onChanged();
                return this;
            }

            /**
             * <code>optional string subscribeHash = 5;</code>
             */
            public Builder setSubscribeHashBytes(final com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                this.bitField0_ |= 0x00000010;
                this.subscribeHash_ = value;
                this.onChanged();
                return this;
            }

            private java.lang.Object publishHash_ = "";

            /**
             * <code>optional string publishHash = 6;</code>
             */
            @Override
            public boolean hasPublishHash() {
                return ((this.bitField0_ & 0x00000020) == 0x00000020);
            }

            /**
             * <code>optional string publishHash = 6;</code>
             */
            @Override
            public java.lang.String getPublishHash() {
                final java.lang.Object ref = this.publishHash_;
                if (!(ref instanceof java.lang.String)) {
                    final com.google.protobuf.ByteString bs = (com.google.protobuf.ByteString) ref;
                    final java.lang.String s = bs.toStringUtf8();
                    if (bs.isValidUtf8()) {
                        this.publishHash_ = s;
                    }
                    return s;
                } else {
                    return (java.lang.String) ref;
                }
            }

            /**
             * <code>optional string publishHash = 6;</code>
             */
            @Override
            public com.google.protobuf.ByteString getPublishHashBytes() {
                final java.lang.Object ref = this.publishHash_;
                if (ref instanceof String) {
                    final com.google.protobuf.ByteString b = com.google.protobuf.ByteString
                            .copyFromUtf8((java.lang.String) ref);
                    this.publishHash_ = b;
                    return b;
                } else {
                    return (com.google.protobuf.ByteString) ref;
                }
            }

            /**
             * <code>optional string publishHash = 6;</code>
             */
            public Builder setPublishHash(final java.lang.String value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                this.bitField0_ |= 0x00000020;
                this.publishHash_ = value;
                this.onChanged();
                return this;
            }

            /**
             * <code>optional string publishHash = 6;</code>
             */
            public Builder clearPublishHash() {
                this.bitField0_ = (this.bitField0_ & ~0x00000020);
                this.publishHash_ = Session.getDefaultInstance().getPublishHash();
                this.onChanged();
                return this;
            }

            /**
             * <code>optional string publishHash = 6;</code>
             */
            public Builder setPublishHashBytes(final com.google.protobuf.ByteString value) {
                if (value == null) {
                    throw new NullPointerException();
                }
                this.bitField0_ |= 0x00000020;
                this.publishHash_ = value;
                this.onChanged();
                return this;
            }

            // @@protoc_insertion_point(builder_scope:message.Session)
        }

        // @@protoc_insertion_point(class_scope:message.Session)
        private static final org.flexiblepower.service.proto.SessionProto.Session DEFAULT_INSTANCE;
        static {
            DEFAULT_INSTANCE = new org.flexiblepower.service.proto.SessionProto.Session();
        }

        public static org.flexiblepower.service.proto.SessionProto.Session getDefaultInstance() {
            return Session.DEFAULT_INSTANCE;
        }

        @java.lang.Deprecated
        public static final com.google.protobuf.Parser<Session> PARSER = new com.google.protobuf.AbstractParser<Session>() {

            @Override
            public Session parsePartialFrom(final com.google.protobuf.CodedInputStream input,
                    final com.google.protobuf.ExtensionRegistryLite extensionRegistry)
                    throws com.google.protobuf.InvalidProtocolBufferException {
                try {
                    return new Session(input, extensionRegistry);
                } catch (final RuntimeException e) {
                    if (e.getCause() instanceof com.google.protobuf.InvalidProtocolBufferException) {
                        throw (com.google.protobuf.InvalidProtocolBufferException) e.getCause();
                    }
                    throw e;
                }
            }
        };

        public static com.google.protobuf.Parser<Session> parser() {
            return Session.PARSER;
        }

        @java.lang.Override
        public com.google.protobuf.Parser<Session> getParserForType() {
            return Session.PARSER;
        }

        @Override
        public org.flexiblepower.service.proto.SessionProto.Session getDefaultInstanceForType() {
            return Session.DEFAULT_INSTANCE;
        }

    }

    private static com.google.protobuf.Descriptors.Descriptor internal_static_message_Session_descriptor;
    private static com.google.protobuf.GeneratedMessage.FieldAccessorTable internal_static_message_Session_fieldAccessorTable;

    public static com.google.protobuf.Descriptors.FileDescriptor getDescriptor() {
        return SessionProto.descriptor;
    }

    private static com.google.protobuf.Descriptors.FileDescriptor descriptor;
    static {
        final java.lang.String[] descriptorData = {"\n\rsession.proto\022\007message\"\255\001\n\007Session\022\'\n\004"
                + "mode\030\001 \002(\0162\031.message.Session.ModeType\022\n\n"
                + "\002id\030\002 \002(\t\022\017\n\007address\030\003 \001(\t\022\014\n\004port\030\004 \001(\005"
                + "\022\025\n\rsubscribeHash\030\005 \001(\t\022\023\n\013publishHash\030\006"
                + " \001(\t\"\"\n\010ModeType\022\n\n\006CREATE\020\000\022\n\n\006DELETE\020\001"
                + "B!\n\021org.flexiblepowerB\014SessionProto"};
        final com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner = new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {

            @Override
            public com.google.protobuf.ExtensionRegistry
                    assignDescriptors(final com.google.protobuf.Descriptors.FileDescriptor root) {
                SessionProto.descriptor = root;
                return null;
            }
        };
        com.google.protobuf.Descriptors.FileDescriptor.internalBuildGeneratedFileFrom(descriptorData,
                new com.google.protobuf.Descriptors.FileDescriptor[] {},
                assigner);
        SessionProto.internal_static_message_Session_descriptor = SessionProto.getDescriptor().getMessageTypes().get(0);
        SessionProto.internal_static_message_Session_fieldAccessorTable = new com.google.protobuf.GeneratedMessage.FieldAccessorTable(
                SessionProto.internal_static_message_Session_descriptor,
                new java.lang.String[] {"Mode", "Id", "Address", "Port", "SubscribeHash", "PublishHash",});
    }

    // @@protoc_insertion_point(outer_class_scope)
}
