from abc import ABCMeta, abstractmethod
from .. import EchoInterfaceConnectionManagerImpl


class EchoInterfaceV001ConnectionHandler:
    """ EchoInterfaceV001ConnectionHandler
        Abstract base class for connection handlers
        Generated by Python code generator for dEF-Pi at Oct 24, 2017 10:43:45 AM by coenvl

        NOTE: This file will be overwritten when the code generator is re-run; any user-made changes will be removed.

        Template by TNO, 2017 """

    __metaclass__ = ABCMeta

    _NAME = "Echo Interface"
    _VERSION = "v0.0.1"
    _RECEIVES_HASH = "a0ab966cd96b57b01298cd8f611880fb01b9108c0f6e8c9e8ec8df133f5d6c54" 
    _SENDS_HASH = "a0ab966cd96b57b01298cd8f611880fb01b9108c0f6e8c9e8ec8df133f5d6c54"
    _MANAGER = EchoInterfaceConnectionManagerImpl
    _SERIALIZER = XSDMessageSerializer 
    _RECEIVES_TYPES = [BooksForm]
    _SENDS_TYPES = [BooksForm]

    @abstractmethod
    def handle_books_form_message(self, message): pass
