from abc import ABCMeta, abstractmethod
from .. import DropbackInterfaceConnectionManagerImpl


class DropbackInterfaceV002ConnectionHandler:
    """ DropbackInterfaceV002ConnectionHandler
        Abstract base class for connection handlers
        Generated by Python code generator for dEF-Pi at Oct 24, 2017 10:43:45 AM by coenvl

        NOTE: This file will be overwritten when the code generator is re-run; any user-made changes will be removed.

        Template by TNO, 2017 """

    __metaclass__ = ABCMeta

    _NAME = "Dropback Interface"
    _VERSION = "v0.0.2"
    _RECEIVES_HASH = "93cb88bbfbd04ef32cf4be90ca2aa9d41fa2eed1f550119fc7ba7bfcd86e8240" 
    _SENDS_HASH = "93cb88bbfbd04ef32cf4be90ca2aa9d41fa2eed1f550119fc7ba7bfcd86e8240"
    _MANAGER = DropbackInterfaceConnectionManagerImpl
    _SERIALIZER = ProtobufMessageSerializer 
    _RECEIVES_TYPES = [Msg, Reply]
    _SENDS_TYPES = [Msg, Reply]

    @abstractmethod
    def handle_msg_message(self, message): pass

    @abstractmethod
    def handle_reply_message(self, message): pass
