package org.flexiblepower.defpi.dashboard;

import javax.annotation.Generated;

/**
 * DashboardConfiguration provides the interface for the Dashboard service
 *
 * File generated by org.flexiblepower.create-service-maven-plugin. 
 * NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
 * Template by TNO, 2017
 * 
 * @author wilco
 */
@Generated(value = "org.flexiblepower.plugin.servicegen", date = "Oct 26, 2017 12:58:33 PM")
public interface DashboardConfiguration {



}