from . import EchoInterfaceConnectionManager
from .V001.EchoInterfaceV001ConnectionHandlerImpl import EchoInterfaceV001ConnectionHandlerImpl


class EchoInterfaceConnectionManagerImpl(EchoInterfaceConnectionManager):
    """ EchoInterfaceConnectionManagerImpl
        Manages all connection handlers for the Echo Service service
        Generated by Python code generator for dEF-Pi at Oct 24, 2017 10:43:45 AM by coenvl

        NOTE: This file is generated as a stub, and has to be implemented by the user. Re-running the codegen plugin 
        will not change the contents of this file.

        Template by TNO, 2017 """

    def __init__(self, service):
        """ Auto-generated constructor building the manager for the provided service """
        self.__service = service

    def build_echo_interface_v001(self, connection):
        """ Build version V001 of the connection handler """
        return EchoInterfaceV001ConnectionHandlerImpl(self.__service, connection)
