from abc import ABCMeta, abstractmethod


class EchoInterfaceConnectionManager:
    """ EchoInterfaceConnectionManager
        Abstract base class for connection handler manager
        Generated by Python code generator for dEF-Pi at Oct 24, 2017 10:43:45 AM by coenvl

        NOTE: This file will be overwritten when the code generator is re-run; any user-made changes will be removed.

        Template by TNO, 2017 """

    __metaclass__ = ABCMeta

    @abstractmethod
    def build_echo_interface_v001(self, connection): pass
