from abc import ABCMeta, abstractmethod
from .. import EchoInterfaceConnectionManagerImpl
from service.model.echo_interface_v001.xsd import BooksForm


class EchoInterfaceV001ConnectionHandler:
    """ EchoInterface_v001ConnectionHandler
        Abstract base class for connection handlers
        Generated by Python code generator for dEF-Pi at Oct 23, 2017 5:18:58 PM by coenvl
    
        NOTE: This file will be overwritten when the codegen plugin is re-run; any user-made changes will be overwritten.
        
        Template by TNO, 2017 """
        
    __metaclass__ = ABCMeta        

    _NAME = "Echo Interface"
    _VERSION = "v001"
    _RECEIVES_HASH = "a0ab966cd96b57b01298cd8f611880fb01b9108c0f6e8c9e8ec8df133f5d6c54" 
    _SENDS_HASH = "a0ab966cd96b57b01298cd8f611880fb01b9108c0f6e8c9e8ec8df133f5d6c54"
    _MANAGER = EchoInterfaceConnectionManagerImpl
    '_SERIALIZER = XSDMessageSerializer'
    _RECEIVES_TYPES = [BooksForm]
    _SENDS_TYPES = [BooksForm]

    @abstractmethod
    def handle_books_form_message(self, message): pass
